'use client';
import {useEffect,useState} from 'react';
import {Input} from '@/components/ui/input';
import {Button} from '@/components/ui/button';
export function AccountSettings(){const [name,setName]=useState(''),[username,setUsername]=useState(''),[current,setCurrent]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{fetch('/api/profile').then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setName(d.name);setUsername(d.username);}).catch(()=>setMessage('دریافت مشخصات حساب ناموفق بود.'));},[]);
 async function save(data:unknown){setBusy(true);setMessage('');try{const r=await fetch('/api/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw Error(d.error||'ذخیره انجام نشد.');if(d.signInAgain){window.location.reload();return;}setMessage('مشخصات ذخیره شد.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <article className="panel"><h2>حساب من</h2><form className="form-grid" onSubmit={e=>{e.preventDefault();void save({name,username});}}><label>نام نمایشی<Input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>نام کاربری نمایشی<Input dir="ltr" maxLength={40} pattern="[a-zA-Z0-9_.-]*" value={username} onChange={e=>setUsername(e.target.value)}/></label><p>ورود همچنان با ایمیل انجام می‌شود؛ نام کاربری شناسه ورود نیست.</p><Button disabled={busy}>ذخیره مشخصات</Button></form><h3>تغییر رمز عبور</h3><form className="form-grid" onSubmit={e=>{e.preventDefault();if(password!==confirm){setMessage('تکرار رمز یکسان نیست.');return;}void save({action:'password',current,password});}}><label>رمز فعلی<Input required type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)}/></label><label>رمز جدید (حداقل ۱۰ کاراکتر)<Input required type="password" minLength={10} maxLength={128} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label>تکرار رمز جدید<Input required type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><p>پس از تغییر رمز، دوباره وارد حساب شوید.</p><Button disabled={busy}>تغییر رمز</Button></form>{message&&<p role="status">{message}</p>}</article>;
}
