'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Pick,PersianDateInput} from './shared';
export type ExtraFilters={city:string;from:string;to:string};
export const emptyFilters:ExtraFilters={city:'all',from:'',to:''};
type Favorite=ExtraFilters&{name:string;query:string;industry:string;filter:string};
export function AdvancedFilters({storageKey,cities,value,onChange,query,industry,filter,onRestore,onReset}:{storageKey:string;cities:string[];value:ExtraFilters;onChange:(v:ExtraFilters)=>void;query:string;industry:string;filter:string;onRestore:(f:Favorite)=>void;onReset:()=>void}){
 const [favorites,setFavorites]=useState<Favorite[]>([]),[name,setName]=useState(''),[error,setError]=useState('');
 useEffect(()=>{let active=true;async function load(){try{const parsed=window.peyvand?await window.peyvand.getPreference(storageKey):JSON.parse(localStorage.getItem(storageKey)||'[]');if(active)setFavorites(Array.isArray(parsed)?parsed.filter(f=>['name','query','industry','filter','city','from','to'].every(k=>typeof f?.[k]==='string')).slice(0,20):[]);}catch{if(active){setFavorites([]);setError('فیلترهای ذخیره‌شده خوانده نشد.');}}}void load();return()=>{active=false;};},[storageKey]);
 async function persist(next:Favorite[]){try{if(window.peyvand)await window.peyvand.setPreference(storageKey,next);else localStorage.setItem(storageKey,JSON.stringify(next));setFavorites(next);setError('');}catch{setError('ذخیره فیلتر ممکن نیست.');}}
 return <section aria-label="فیلترهای تکمیلی"><div className="advanced-filters"><label>شهر<Pick label="فیلتر شهر" value={value.city} onChange={city=>onChange({...value,city})} options={[{value:'all',label:'همه شهرها'},...cities.map(v=>({value:v,label:v}))]}/></label><label>ثبت از تاریخ<PersianDateInput value={value.from} onChange={from=>onChange({...value,from})} ariaLabel="تاریخ ثبت از"/></label><label>ثبت تا تاریخ<PersianDateInput value={value.to} onChange={to=>onChange({...value,to})} ariaLabel="تاریخ ثبت تا"/></label><Button variant="outline" onClick={onReset}>پاک‌کردن فیلترها</Button></div>{value.from&&value.to&&value.from>value.to&&<p role="alert" className="error">تاریخ شروع باید پیش از پایان باشد.</p>}<div className="filter-favorites"><Input aria-label="نام فیلتر دلخواه" placeholder="نام فیلتر دلخواه…" maxLength={50} style={{maxWidth:200}} value={name} onChange={e=>setName(e.target.value)}/><Button variant="outline" disabled={!name.trim()||favorites.length>=20} onClick={()=>{persist([...favorites.filter(f=>f.name!==name.trim()),{...value,name:name.trim(),query,industry,filter}]);setName('');}}>ذخیره فیلتر</Button>{favorites.map(f=><span className="row" key={f.name}><Button variant="outline" onClick={()=>onRestore(f)}>{f.name}</Button><Button size="icon" variant="ghost" aria-label={'حذف فیلتر '+f.name} onClick={()=>persist(favorites.filter(x=>x.name!==f.name))}>×</Button></span>)}</div>{error&&<p role="alert">{error}</p>}</section>;
}
