'use client';
import {useMemo,useState} from 'react';
import {Area,AreaChart,Bar,BarChart,CartesianGrid,XAxis,YAxis,Pie,PieChart,Cell,Tooltip} from 'recharts';
import {ArrowUpLeft,ArrowDownLeft,ChartNoAxesCombined,Boxes,CheckCheck,Clock3,FileCheck2,Target,TrendingUp,AlertTriangle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {ChartContainer} from '@/components/ui/chart';
import {Progress} from '@/components/ui/progress';
import {Pick,NoRows,num,short,money,date} from './shared';
import {stages,stageLabels,quoteStatuses,quoteStatusLabels,quoteAmounts,localDay,addDays,type Row,type Audit} from '@/lib/crm';

export function Dashboard({rows,audit,onNavigate,onOpen}:{rows:Row[];audit:Audit[];onNavigate:(v:string,filter?:string)=>void;onOpen:(id:string)=>void}){
 const [period,setPeriod]=useState('90');
 const now=localDay(),cutoff=period==='all'?'0000-01-01':addDays(now,-Number(period)+1);
 const deals=rows.filter(r=>r.kind==='deals'&&r.created_at.slice(0,10)>=cutoff);
 const won=deals.filter(r=>r.data.stage==='won'),closed=deals.filter(r=>['won','lost'].includes(r.data.stage));
 const revenue=won.reduce((sum,r)=>sum+r.data.amount,0),open=deals.filter(r=>!['won','lost'].includes(r.data.stage));
 const pipeline=open.reduce((sum,r)=>sum+r.data.amount,0),winRate=closed.length?Math.round(won.length/closed.length*100):0;
 const tasks=rows.filter(r=>r.kind==='tasks'&&r.data.status==='open').sort((a,b)=>(a.data.due||'9999').localeCompare(b.data.due||'9999'));
 const late=tasks.filter(r=>r.data.due&&r.data.due<now),todayTasks=tasks.filter(r=>r.data.due===now);
 const products=rows.filter(r=>r.kind==='products'&&r.data.status==='active'),lowStock=products.filter(r=>r.data.stock<=r.data.min_stock);
 const quotes=rows.filter(r=>r.kind==='proformas'&&r.created_at.slice(0,10)>=cutoff);
 const quoteData=quoteStatuses.map((status,i)=>({name:quoteStatusLabels[status],status,value:quotes.filter(r=>r.data.quote_status===status).length,fill:['#8dabc1','#e8b655','#36ad95','#d5776b'][i]}));
 const stageData=stages.map((stage,i)=>({stage,name:stageLabels[stage],count:deals.filter(r=>r.data.stage===stage).length,value:deals.filter(r=>r.data.stage===stage).reduce((s,r)=>s+r.data.amount,0),fill:['#bad5cd','#80bcac','#37a78d','#177e65','#15553f','#dfb4a5'][i]}));
 const trend=useMemo(()=>{
  const eligible=rows.filter(r=>r.kind==='deals'&&r.created_at.slice(0,10)>=cutoff);
  const first=period==='all'?eligible.reduce((s,r)=>r.created_at.slice(0,10)<s?r.created_at.slice(0,10):s,addDays(now,-89)):cutoff;
  const span=Math.max(1,Math.round((Date.parse(now)-Date.parse(first))/86400000)+1),size=Math.max(1,Math.ceil(span/8));
  return Array.from({length:Math.ceil(span/size)},(_,i)=>{const start=addDays(first,i*size),end=addDays(first,(i+1)*size);const list=eligible.filter(r=>r.created_at.slice(0,10)>=start&&r.created_at.slice(0,10)<end);return {label:new Intl.DateTimeFormat('fa-IR-u-ca-persian',{month:'short',day:'numeric'}).format(new Date(start+'T12:00:00')),value:list.reduce((s,r)=>s+r.data.amount,0),won:list.filter(r=>r.data.stage==='won').reduce((s,r)=>s+r.data.amount,0)};});
 },[rows,cutoff,now,period]);
 const pendingQuotes=quotes.filter(r=>['draft','sent'].includes(r.data.quote_status)).reduce((s,r)=>s+quoteAmounts(r.data).total,0);
 return <div className="dashboard-v5">
  <section className="overview-banner"><div><span className="overview-kicker">مرکز مدیریت فروش</span><h2>تصویر روشنِ کسب‌وکار شما</h2><p>فروش، پیگیری‌ها و موجودی در یک نگاه.</p><div className="overview-meta"><span><Clock3 size={16}/>{num(todayTasks.length)} پیگیری امروز</span><span><Boxes size={16}/>{num(products.length)} محصول فعال</span></div></div><div className="overview-control"><span>بازهٔ ثبت فرصت‌ها و پیش‌فاکتورها</span><Pick label="بازه داشبورد" value={period} onChange={setPeriod} options={[{value:'30',label:'۳۰ روز گذشته'},{value:'90',label:'۹۰ روز گذشته'},{value:'all',label:'کل دوره'}]}/><small>انبار و پیگیری‌ها: وضعیت فعلی</small></div></section>
  <section className="overview-metrics">
   <button className="overview-stat stat-dark" onClick={()=>onNavigate('deals','won')}><div><span>فروش موفق</span><TrendingUp size={22}/></div><strong>{short(revenue)}</strong><span className="stat-unit">تومان · {num(won.length)} فرصت موفق</span><span className="stat-link">مشاهده فروش‌ها <ArrowUpLeft size={16}/></span></button>
   <button className="overview-stat" onClick={()=>onNavigate('deals')}><div><span>ارزش فرصت‌های باز</span><Target size={22}/></div><strong>{short(pipeline)}</strong><span className="stat-unit">تومان · {num(open.length)} فرصت در جریان</span><span className="stat-link">ورود به پایپ‌لاین <ArrowUpLeft size={16}/></span></button>
   <button className="overview-stat" onClick={()=>onNavigate('proformas')}><div><span>پیش‌فاکتورهای در انتظار</span><FileCheck2 size={22}/></div><strong>{short(pendingQuotes)}</strong><span className="stat-unit">تومان · پیش‌نویس و ارسال‌شده</span><span className="stat-link">مشاهده پیش‌فاکتورها <ArrowUpLeft size={16}/></span></button>
   <button className={'overview-stat '+(lowStock.length?'stat-warm':'')} onClick={()=>onNavigate('inventory','low')}><div><span>نیاز به تأمین کالا</span><Boxes size={22}/></div><strong>{num(lowStock.length)}<em> محصول</em></strong><span className="stat-unit">موجودی برابر یا کمتر از حداقل</span><span className="stat-link">بررسی انبار <ArrowUpLeft size={16}/></span></button>
  </section>
  <section className="analytics-grid"><article className="panel trend-panel"><div className="section-title"><div><h2><ChartNoAxesCombined size={20}/> روند فرصت‌های فروش</h2><p>مبلغ فرصت‌ها بر اساس تاریخ ثبت؛ تومان</p></div><span className="chart-legend"><i/>کل فرصت‌ها <i className="legend-won"/>موفق</span></div>
   {deals.length?<ChartContainer config={{value:{label:'کل فرصت‌ها',color:'#2b9b80'},won:{label:'فرصت موفق',color:'#bc8c34'}}} className="dashboard-chart"><AreaChart data={trend} accessibilityLayer margin={{top:10,left:18,right:5,bottom:5}}><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2b9b80" stopOpacity={0.3}/><stop offset="100%" stopColor="#2b9b80" stopOpacity={0.02}/></linearGradient></defs><CartesianGrid vertical={false} strokeDasharray="4 5"/><XAxis dataKey="label" tickLine={false} axisLine={false} tickMargin={12}/><YAxis tickFormatter={v=>short(Number(v))} tickLine={false} axisLine={false} width={80}/><Tooltip formatter={(v,name)=>[money(Number(v)),name==='value'?'کل فرصت‌ها':'فرصت‌های موفق']} contentStyle={{fontFamily:'inherit',borderRadius:12,direction:'rtl',borderColor:'#dbe7e1'}}/><Area type="monotone" dataKey="value" stroke="#2b9b80" fill="url(#revenueFill)" strokeWidth={3}/><Area type="monotone" dataKey="won" stroke="#bc8c34" fill="transparent" strokeWidth={2} strokeDasharray="5 3"/></AreaChart></ChartContainer>:<NoRows title="روند فروش از اینجا شکل می‌گیرد" description="با ثبت فرصت فروش، نمودار این بازه نمایش داده می‌شود."/>}
  </article><article className="panel conversion-panel"><div className="section-title"><h2>نتیجهٔ مذاکرات</h2><CheckCheck size={20}/></div><div className="conversion-rate">{num(winRate)}<span>٪</span></div><p>نرخ موفقیت در فرصت‌های بسته‌شده</p><Progress value={winRate} className="conversion-progress"/><div className="conversion-breakdown"><span><b>{num(won.length)}</b>موفق</span><span><b>{num(closed.length-won.length)}</b>ناموفق</span><span><b>{num(open.length)}</b>در جریان</span></div><Button variant="outline" onClick={()=>onNavigate('deals')}>مدیریت فرصت‌ها <ArrowUpLeft size={16}/></Button></article></section>
  <section className="analytics-grid secondary-analytics"><article className="panel"><div className="section-title"><div><h2>توزیع ارزش پایپ‌لاین</h2><p>مبلغ فرصت‌ها در هر مرحله، به تومان</p></div><Button variant="ghost" onClick={()=>onNavigate('deals')}>پایپ‌لاین <ArrowUpLeft size={16}/></Button></div><ChartContainer className="dashboard-chart stage-chart" config={{value:{label:'مبلغ',color:'#2b9b80'}}}><BarChart data={stageData} accessibilityLayer margin={{left:5,right:10,bottom:14}}><CartesianGrid vertical={false} strokeDasharray="4 5"/><XAxis dataKey="name" tickLine={false} axisLine={false} interval={0}/><YAxis tickFormatter={v=>short(Number(v))} axisLine={false} tickLine={false} width={75}/><Tooltip formatter={v=>[money(Number(v)),'مبلغ']} contentStyle={{direction:'rtl',fontFamily:'inherit',borderRadius:12}}/><Bar dataKey="value" radius={[7,7,0,0]} maxBarSize={50}>{stageData.map(s=><Cell key={s.stage} fill={s.fill}/>)}</Bar></BarChart></ChartContainer></article>
  <article className="panel quote-chart-panel"><div className="section-title"><h2>وضعیت پیش‌فاکتورها</h2><span className="count">{num(quotes.length)}</span></div>{quotes.length?<div className="donut-layout"><ChartContainer config={{value:{label:'تعداد'}}} className="donut-chart"><PieChart accessibilityLayer><Pie data={quoteData.filter(s=>s.value)} dataKey="value" nameKey="name" innerRadius="64%" outerRadius="92%" paddingAngle={4} strokeWidth={0}>{quoteData.filter(s=>s.value).map(s=><Cell key={s.status} fill={s.fill}/>)}</Pie><Tooltip formatter={v=>[num(Number(v)),'پیش‌فاکتور']}/></PieChart></ChartContainer><div className="donut-legend">{quoteData.map(s=><button key={s.status} onClick={()=>onNavigate('proformas',s.status)}><i style={{background:s.fill}}/><span>{s.name}</span><b>{num(s.value)}</b></button>)}</div></div>:<NoRows title="پیش‌فاکتوری در این بازه نیست" description="پیش‌فاکتور تازه بسازید یا بازه را تغییر دهید."/>}</article></section>
  <section className="action-grid"><article className="panel"><div className="section-title"><h2>قدم‌های بعدی</h2><span className={'badge '+(late.length?'rejected':'active')}>{num(late.length)} عقب‌افتاده</span></div>{tasks.slice(0,4).map(r=><button className="dashboard-action" key={r.id} onClick={()=>onOpen(r.id)}><span className={'action-icon '+(r.data.due&&r.data.due<now?'warm':'')}><Clock3 size={19}/></span><span><b>{r.data.name}</b><small>{rows.find(p=>p.id===r.parent_id)?.data.name||'بدون مشتری'} · {date(r.data.due)}</small></span><ArrowUpLeft size={16}/></button>)}{!tasks.length&&<NoRows title="پیگیری بازی ندارید" description="برای هر فرصت، قدم بعدی را مشخص کنید."/>}<Button variant="ghost" onClick={()=>onNavigate('tasks')}>همهٔ پیگیری‌ها</Button></article>
  <article className="panel"><div className="section-title"><h2>کنترل موجودی</h2><AlertTriangle size={20}/></div>{lowStock.slice(0,4).map(r=><button className="dashboard-action" key={r.id} onClick={()=>onNavigate('inventory','low')}><span className="action-icon warm"><Boxes size={19}/></span><span><b>{r.data.name}</b><small>موجودی {num(r.data.stock)} {r.data.unit} · حداقل {num(r.data.min_stock)}</small></span><ArrowUpLeft size={16}/></button>)}{!lowStock.length&&<NoRows title={products.length?'موجودی محصولات کافی است':'هنوز محصولی ثبت نشده'} description="حداقل موجودی هر محصول را در کاتالوگ تنظیم کنید."/>}<Button variant="ghost" onClick={()=>onNavigate('inventory')}>مدیریت انبار</Button></article>
  <article className="panel"><div className="section-title"><h2>آخرین تغییرات</h2><span className="count">{num(audit.length)}</span></div>{audit.slice(0,4).map(a=><div className="dashboard-action audit-row" key={a.id}><span className="action-icon"><ArrowDownLeft size={18}/></span><span><b>{a.label}</b><small>{a.action==='INSERT'?'ثبت شد':a.action==='DELETE'?'حذف شد':'ویرایش شد'} · {date(a.created_at)}</small></span></div>)}{!audit.length&&<NoRows title="هنوز تغییری ثبت نشده" description="تاریخچهٔ فعالیت‌ها اینجا نمایش داده می‌شود."/>}</article></section>
  <p className="table-note">«فروش موفق» مبلغ فرصت‌های موفق است؛ به معنی دریافت وجه نیست.</p>
 </div>;
}
