'use client';
import {NumberInput} from '@/components/ui/number-input';
import {DealAmount,DealDue} from './deal-fields';
import {useState,type FormEvent} from 'react';
import {Plus,Trash2,Package} from 'lucide-react';
import {toast} from 'sonner';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {blank,dataSchema,validateSales,quoteAmounts,nextQuoteNumber,addDays,localDay,labels,stages,stageLabels,quoteStatusLabels,automationTriggerLabels,automationActionLabels,activityTypeLabels,activityDirectionLabels,type Data,type Row,type Kind,type State,type ProformaItem} from '@/lib/crm';
import {PersianDateInput,Pick,money,num,priorityLabels} from './shared';
import {duplicateReasons} from '@/lib/workflow-tools';
import {BusinessFields} from './business-fields';
export type Editing={kind:Kind;row?:Row;parent?:string;intent?:'lead';preset?:Partial<Data>};
export function Editor({editing,rows,members,busy,onClose,onSave}:{editing:Editing;rows:Row[];members:State['members'];busy:boolean;onClose:()=>void;onSave:(d:Data,p:string|null)=>void}){
 const kind=editing.kind;
 const [choosingProduct,setChoosingProduct]=useState(false);
 const [productSearch,setProductSearch]=useState('');
 const [productType,setProductType]=useState('all');
 const productTypes={paint:'رنگ',primer:'آستر',clearcoat:'کیلر',other:'سایر'};
 const [allowDuplicate,setAllowDuplicate]=useState(false);
 const [data,setData]=useState<Data>(()=>editing.row?.data||{...blank(),...editing.preset,name:editing.preset?.name||'',status:['tasks','activities'].includes(kind)?'open':editing.intent==='lead'?'lead':'active',quote_number:kind==='proformas'?nextQuoteNumber(rows):'',valid_until:kind==='proformas'?addDays(localDay(),14):''});
 const initialParent=editing.row?.parent_id||editing.parent||'';
 const [parent,setParent]=useState(initialParent);
 const [customerIndustry,setCustomerIndustry]=useState('');
 const [customerSearch,setCustomerSearch]=useState('');
 const companies=rows.filter(r=>r.kind==='companies');
 const customerIndustries=[...new Set(companies.map(r=>r.data.industry.trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'fa'));
 const searchText=(s:string)=>s.toLowerCase().replace(/ي/g,'ی').replace(/ك/g,'ک').trim();
 const matchingCompanies=companies.filter(r=>(!customerIndustry||r.data.industry.trim()===customerIndustry)&&(!customerSearch||searchText(r.data.name).includes(searchText(customerSearch))));
 const selectedCustomer=companies.find(r=>r.id===parent);
 const contactOptions=(customerIndustry||customerSearch?matchingCompanies:[]);
 const visibleCustomers=selectedCustomer&&!contactOptions.some(r=>r.id===parent)?[selectedCustomer,...contactOptions]:contactOptions;

 const [activityRelationKind,setActivityRelationKind]=useState(()=>kind==='activities'?(rows.find(r=>r.id===initialParent)?.kind||''):'');
 const set=(key:keyof Data,value:unknown)=>{setAllowDuplicate(false);setData(current=>({...current,[key]:value} as Data));};
 const duplicates=['companies','contacts'].includes(kind)?rows.filter(r=>r.kind===kind&&r.id!==editing.row?.id&&duplicateReasons(data,r.data).length):[];
 const products=rows.filter(r=>r.kind==='products'&&!r.data.archived&&r.data.status==='active');
 const relationLabels:Record<string,string>={companies:'حساب',contacts:'کانتکت',deals:'فرصت فروش'};
 const activityRelations=rows.filter(r=>r.kind===activityRelationKind);
 const updateItem=(index:number,patch:Partial<ProformaItem>)=>setData(d=>({...d,items:d.items.map((item,i)=>i===index?{...item,...patch}:item)}));
 const addItem=(p:Row)=>{setData(d=>({...d,items:[...d.items,{product_id:p.id,name:p.data.name,unit:p.data.unit,quantity:1,unit_price:p.data.price}]}));setChoosingProduct(false);};
 const availableProducts=products.filter(p=>(productType==='all'||p.data.product_type===productType)&&searchText([p.data.name,p.data.sku,p.data.ral_code].join(' ')).includes(searchText(productSearch)));

 const totals=quoteAmounts(data),title=editing.intent==='lead'?'سرنخ':labels[kind];
 function submit(e:FormEvent){e.preventDefault();const parsed=dataSchema.safeParse(data);if(!parsed.success)return toast.error(parsed.error.issues[0].message);const error=validateSales(kind,parsed.data);if(error)return toast.error(error);if(kind==='proformas'&&!parent)return toast.error('مشتری پیش‌فاکتور را انتخاب کنید.');if(duplicates.length&&!allowDuplicate)return toast.error('مورد مشابه وجود دارد؛ ابتدا هشدار تکراری را بررسی کنید.');onSave(parsed.data,parent||null);}
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent dir="rtl" className={'editor-dialog '+(kind==='proformas'?'quote-editor':'')}><DialogTitle>{editing.row?'ویرایش':'ثبت'} {title}</DialogTitle><DialogDescription>{kind==='proformas'?'اقلام، مقدار و مبلغ را بررسی کنید. تمام مبالغ به تومان است.':kind==='activities'?'نوع فعالیت، زمان، مسئول و ارتباط آن را ثبت کنید.':'اطلاعات را وارد کنید و ذخیره را بزنید.'}</DialogDescription>
 <form className="form-grid" onSubmit={submit}>
 <label className="full">{kind==='contacts'?'نام و نام خانوادگی':kind==='tasks'?'عنوان پیگیری':kind==='proformas'?'عنوان پیش‌فاکتور':kind==='automations'?'نام قانون':'نام / عنوان'}<Input autoFocus required maxLength={160} value={data.name} onChange={e=>set('name',e.target.value)}/></label>
 <BusinessFields kind={kind} data={data} set={set}/>
 {['contacts','proformas'].includes(kind)&&<><label>فیلتر حوزه فعالیت مشتری<Pick label="فیلتر حوزه فعالیت مشتری" value={customerIndustry} onChange={setCustomerIndustry} options={[{value:'',label:'انتخاب حوزه فعالیت'},...customerIndustries.map(value=>({value,label:value}))]}/></label><label>جست‌وجوی شرکت<Input value={customerSearch} onChange={e=>setCustomerSearch(e.target.value)} placeholder="نام شرکت را بنویسید"/></label><label className="full">مشتری مرتبط<Pick label="مشتری مرتبط" value={parent} onChange={v=>{setParent(v);if(kind==='proformas')set('related_deal_id','');}} options={[{value:'',label:'انتخاب مشتری'},...visibleCustomers.map(r=>({value:r.id,label:r.data.name}))]}/><small>{!customerIndustry&&!customerSearch?'برای یافتن شرکت، حوزه فعالیت را انتخاب کنید یا نام آن را بنویسید.':!matchingCompanies.length?'شرکتی با این فیلتر پیدا نشد.':''}</small></label>{kind==='contacts'&&<label>حوزه فعالیت<Input maxLength={100} value={data.industry} placeholder={selectedCustomer?.data.industry||'حوزه فعالیت مخاطب'} onChange={e=>set('industry',e.target.value)}/><small>اگر خالی باشد، حوزه فعالیت مشتری مرتبط استفاده می‌شود.</small></label>}</>}
 {['deals','tasks'].includes(kind)&&<label className="full">مشتری مرتبط<Pick label="مشتری مرتبط" value={parent} onChange={setParent} options={[{value:'',label:kind==='proformas'?'انتخاب مشتری':'بدون مشتری'},...rows.filter(r=>r.kind==='companies').map(r=>({value:r.id,label:r.data.name}))]}/></label>}
 {kind==='activities'&&<><label>نوع ارتباط<Pick label="نوع ارتباط" value={activityRelationKind} onChange={v=>{setActivityRelationKind(v);setParent('');}} options={[{value:'',label:'بدون ارتباط'},{value:'companies',label:'حساب'},{value:'contacts',label:'کانتکت'},{value:'deals',label:'فرصت فروش'}]}/></label>{activityRelationKind?<label>مرتبط با<Pick label={'انتخاب '+(relationLabels[activityRelationKind]||'رکورد')} value={parent} onChange={setParent} options={[{value:'',label:'انتخاب کنید'},...activityRelations.map(r=>({value:r.id,label:r.data.name}))]}/></label>:<div className="activity-relation-empty"><span>بدون ارتباط</span><small>در صورت نیاز ابتدا نوع ارتباط را انتخاب کنید.</small></div>}</>}
 {(kind==='companies'||kind==='contacts')&&<><label>ایمیل<Input type="email" dir="ltr" value={data.email} onChange={e=>set('email',e.target.value)}/></label><label>تلفن<Input dir="ltr" maxLength={50} value={data.phone} onChange={e=>set('phone',e.target.value)}/></label><label>{kind==='companies'?'حوزهٔ فعالیت':'سمت'}<Input maxLength={100} value={kind==='companies'?data.industry:data.position} onChange={e=>set(kind==='companies'?'industry':'position',e.target.value)}/></label><label>شهر<Input maxLength={100} value={data.city} onChange={e=>set('city',e.target.value)}/></label><label>وضعیت<Pick label="وضعیت" value={data.status} onChange={v=>set('status',v)} options={[{value:'active',label:'مشتری فعال'},{value:'lead',label:'سرنخ'},{value:'inactive',label:'غیرفعال'}]}/></label></>}
 {kind==='products'&&<><label>نوع محصول<Pick label="نوع محصول" value={data.product_type} onChange={v=>set('product_type',v)} options={Object.entries(productTypes).map(([value,label])=>({value,label}))}/></label><label>کد رال رنگ<Input dir="ltr" maxLength={30} placeholder="مثلاً RAL 3020" value={data.ral_code} onChange={e=>set('ral_code',e.target.value)}/></label><label>کد محصول (SKU)<Input dir="ltr" maxLength={80} value={data.sku} onChange={e=>set('sku',e.target.value)}/></label><label>دسته‌بندی<Input maxLength={100} value={data.category} onChange={e=>set('category',e.target.value)}/></label><label>واحد فروش<Input required maxLength={30} placeholder="عدد، کیلوگرم، لیتر…" value={data.unit} onChange={e=>set('unit',e.target.value)}/></label><label>قیمت فروش (تومان)<NumberInput type="number" dir="ltr" min={0} max={1e15} step="1" value={data.price} onChange={e=>set('price',Number(e.target.value))}/></label><label>{editing.row?'موجودی فعلی':'موجودی اولیه'}<NumberInput type="number" dir="ltr" readOnly={!!editing.row} min={0} max={1e12} step="0.01" value={data.stock} onChange={e=>set('stock',Number(e.target.value))}/>{editing.row&&<small>تغییر موجودی از بخش انبارداری</small>}</label><label>حداقل موجودی<NumberInput type="number" dir="ltr" min={0} max={1e12} step="0.01" value={data.min_stock} onChange={e=>set('min_stock',Number(e.target.value))}/></label><label>وضعیت<Pick label="وضعیت محصول" value={data.status} onChange={v=>set('status',v)} options={[{value:'active',label:'فعال'},{value:'inactive',label:'غیرفعال'}]}/></label></>}
 {kind==='proformas'&&<><label>فرصت فروش مرتبط<Pick label="فرصت فروش مرتبط" value={data.related_deal_id} onChange={v=>set('related_deal_id',v)} options={[{value:'',label:'بدون فرصت مرتبط'},...rows.filter(r=>r.kind==='deals'&&r.parent_id===parent).map(r=>({value:r.id,label:r.data.name}))]}/></label><label>شمارهٔ پیش‌فاکتور<Input required dir="ltr" maxLength={80} value={data.quote_number} onChange={e=>set('quote_number',e.target.value)}/></label><label>وضعیت<Pick label="وضعیت پیش‌فاکتور" value={data.quote_status} onChange={v=>set('quote_status',v)} options={Object.entries(quoteStatusLabels).map(([value,label])=>({value,label}))}/></label><label>پایان اعتبار<PersianDateInput value={data.valid_until} onChange={v=>set('valid_until',v)} ariaLabel="تاریخ اعتبار پیش‌فاکتور به شمسی"/></label><div className="full quote-line-editor"><div className="section-title"><h3><Package size={18}/> اقلام پیش‌فاکتور</h3><Button variant="outline" type="button" disabled={data.items.length>=100} onClick={()=>{setProductSearch('');setProductType('all');setChoosingProduct(true);}}><Plus size={16}/>افزودن محصول</Button></div><div className="quote-line-head"><span>محصول</span><span>مقدار</span><span>قیمت واحد</span><span>مبلغ ردیف</span><span/></div>{data.items.map((item,index)=><div className="quote-line" key={index}><div><b>{item.name}</b><small>{item.unit||'عدد'}</small></div><NumberInput aria-label={'مقدار ردیف '+(index+1)} required type="number" min="0.01" max={1e6} step="0.01" value={item.quantity} onChange={e=>updateItem(index,{quantity:Number(e.target.value)})}/><output aria-label={'قیمت واحد ردیف '+(index+1)} dir="ltr">{num(item.unit_price)}</output><strong>{num(totals.lines[index])}</strong><Button variant="ghost" size="icon" type="button" aria-label={'حذف ردیف '+(index+1)} onClick={()=>set('items',data.items.filter((_,i)=>i!==index))}><Trash2 size={16}/></Button></div>)}{!data.items.length&&<p className="muted">برای شروع یک محصول اضافه کنید.</p>}</div><label>تخفیف (درصد)<NumberInput type="number" dir="ltr" min={0} max={100} step="0.01" value={data.discount_percent} onChange={e=>set('discount_percent',Number(e.target.value))}/></label><label>مالیات (درصد)<NumberInput type="number" dir="ltr" min={0} max={100} step="0.01" value={data.tax_percent} onChange={e=>set('tax_percent',Number(e.target.value))}/></label><div className="full quote-summary"><span>جمع اقلام <b>{money(totals.subtotal)}</b></span><span>تخفیف <b>{money(totals.discount)}</b></span><span>مالیات <b>{money(totals.tax)}</b></span><strong>مبلغ نهایی <b>{money(totals.total)}</b></strong></div></>}
 {kind==='automations'&&<><label>زمان اجرا<Pick label="محرک قانون" value={data.automation_trigger} onChange={v=>set('automation_trigger',v)} options={Object.entries(automationTriggerLabels).map(([value,label])=>({value,label}))}/></label><label>اقدام<Pick label="اقدام قانون" value={data.automation_action} onChange={v=>set('automation_action',v)} options={Object.entries(automationActionLabels).map(([value,label])=>({value,label}))}/></label>{data.automation_trigger==='stage_change'&&<label>مرحلهٔ مقصد<Pick label="مرحله مقصد" value={data.automation_stage} onChange={v=>set('automation_stage',v)} options={stages.map(value=>({value,label:stageLabels[value]}))}/></label>}<label>{data.automation_trigger==='quote_expiry'?'چند روز پیش از پایان اعتبار':'موعد پیگیری چند روز بعد باشد؟'}<NumberInput type="number" min={0} max={365} step="1" value={data.automation_days} onChange={e=>set('automation_days',Number(e.target.value))}/></label><label>وضعیت قانون<Pick label="وضعیت قانون" value={data.automation_enabled&&data.status==='active'?'active':'inactive'} onChange={v=>setData(d=>({...d,status:v as Data['status'],automation_enabled:v==='active'}))} options={[{value:'active',label:'فعال'},{value:'inactive',label:'غیرفعال'}]}/></label><p className="muted full">قانون‌های زمانی هنگام بازبودن برنامه و تازه‌سازی اطلاعات بررسی می‌شوند؛ تغییر مرحله هنگام ذخیره فرصت بررسی می‌شود.</p></>}
 {kind==='deals'&&<><label>مبلغ فرصت (تومان)<DealAmount value={data.amount} onChange={value=>set('amount',value)}/></label><label>مرحلهٔ فروش<Pick label="مرحله فروش" value={data.stage} onChange={v=>set('stage',v)} options={stages.map(value=>({value,label:stageLabels[value]}))}/></label></>}
 {(kind==='deals'||kind==='tasks'||kind==='activities')&&<><label>{kind==='activities'?'تاریخ فعالیت':'موعد'}<PersianDateInput value={data.due} onChange={v=>set('due',v)} ariaLabel="موعد به شمسی"/><DealDue value={data.due}/></label><label>مسئول<Pick label="مسئول" value={data.assignee} onChange={v=>set('assignee',v)} options={[{value:'',label:'تعیین نشده'},...members.map(m=>({value:m.user_id,label:m.email}))]}/></label></>}
 {kind==='activities'&&<><label>نوع فعالیت<Pick label="نوع فعالیت" value={data.activity_type} onChange={v=>set('activity_type',v)} options={Object.entries(activityTypeLabels).map(([value,label])=>({value,label}))}/></label><label>جهت<Pick label="جهت فعالیت" value={data.activity_direction} onChange={v=>set('activity_direction',v)} options={Object.entries(activityDirectionLabels).map(([value,label])=>({value,label}))}/></label><label>ساعت شروع<Input type="time" dir="ltr" value={data.activity_time} onChange={e=>set('activity_time',e.target.value)}/></label><label>ساعت پایان<Input type="time" dir="ltr" value={data.activity_end_time} onChange={e=>set('activity_end_time',e.target.value)}/></label><label className="full">محل / لینک جلسه<Input maxLength={300} value={data.activity_location} onChange={e=>set('activity_location',e.target.value)}/></label><label className="full">نتیجه فعالیت<Input maxLength={500} value={data.activity_result} onChange={e=>set('activity_result',e.target.value)}/></label></>}
 {['tasks','activities'].includes(kind)&&<><label>اولویت<Pick label="اولویت" value={data.priority} onChange={v=>set('priority',v)} options={Object.entries(priorityLabels).map(([value,label])=>({value,label}))}/></label><label>وضعیت<Pick label={kind==='activities'?'وضعیت فعالیت':'وضعیت پیگیری'} value={data.status} onChange={v=>set('status',v)} options={[{value:'open',label:'باز'},{value:'done',label:'انجام‌شده'}]}/></label></>}
 <label className="full">{kind==='automations'?'متن پیگیری یا یادآوری':'توضیحات'}<Textarea rows={3} maxLength={10000} value={data.description} onChange={e=>set('description',e.target.value)}/></label>{duplicates.length>0&&<div className="full duplicate-warning" role="alert"><b>اطلاعات مشابه پیدا شد</b>{duplicates.slice(0,5).map(r=><p key={r.id}>{r.data.name} · {r.data.phone} · {duplicateReasons(data,r.data).join('، ')}</p>)}<label><input type="checkbox" checked={allowDuplicate} onChange={e=>setAllowDuplicate(e.target.checked)}/>بررسی کردم؛ این رکورد جداگانه ذخیره شود.</label></div>}<div className="row full form-actions"><Button disabled={busy} type="submit" className="primary">{busy?'در حال ذخیره…':'ذخیره اطلاعات'}</Button><Button type="button" variant="outline" disabled={busy} onClick={onClose}>انصراف</Button></div>
 {choosingProduct&&<section className="full product-picker" aria-label="انتخاب محصول از انبار"><div className="section-title"><h3>انتخاب محصول از انبار</h3><Button type="button" variant="outline" onClick={()=>setChoosingProduct(false)}>بستن فهرست</Button></div><Input autoFocus aria-label="جست‌وجوی محصول" placeholder="نام محصول، کد یا رال…" value={productSearch} onChange={e=>setProductSearch(e.target.value)}/><Pick label="فیلتر نوع محصول" value={productType} onChange={setProductType} options={[{value:'all',label:'همه انواع'},...Object.entries(productTypes).map(([value,label])=>({value,label}))]}/><div className="product-picker-results">{availableProducts.map(p=><Button className="product-picker-item" variant="outline" type="button" key={p.id} disabled={data.items.some(i=>i.product_id===p.id)} onClick={()=>addItem(p)}><span>{p.data.name}<small>{productTypes[p.data.product_type]} · {p.data.sku} {p.data.ral_code}</small></span><span>موجودی: {num(p.data.stock)} {p.data.unit}<small>{money(p.data.price)}{data.items.some(i=>i.product_id===p.id)?' · اضافه شده':''}</small></span></Button>)}{!availableProducts.length&&<p>محصولی پیدا نشد.</p>}</div></section>}
 </form></DialogContent></Dialog>;
}