'use client';
import {DealAmount,DealDue} from './deal-fields';
import {useState,type FormEvent} from 'react';
import {Plus,Trash2,Package} from 'lucide-react';
import {toast} from 'sonner';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {blank,dataSchema,validateSales,quoteAmounts,nextQuoteNumber,addDays,localDay,labels,stages,stageLabels,quoteStatusLabels,automationTriggerLabels,automationActionLabels,activityTypeLabels,activityDirectionLabels,type Data,type Row,type Kind,type State,type ProformaItem} from '@/lib/crm';
import {PersianDateInput,Pick,money,num,priorityLabels} from './shared';
import {BusinessFields} from './business-fields';
export type Editing={kind:Kind;row?:Row;parent?:string;intent?:'lead'};
export function Editor({editing,rows,members,busy,onClose,onSave}:{editing:Editing;rows:Row[];members:State['members'];busy:boolean;onClose:()=>void;onSave:(d:Data,p:string|null)=>void}){
 const kind=editing.kind;
 const [data,setData]=useState<Data>(()=>editing.row?.data||{...blank(),name:'',status:['tasks','activities'].includes(kind)?'open':editing.intent==='lead'?'lead':'active',quote_number:kind==='proformas'?nextQuoteNumber(rows):'',valid_until:kind==='proformas'?addDays(localDay(),14):''});
 const [parent,setParent]=useState(editing.row?.parent_id||editing.parent||'');
 const set=(key:keyof Data,value:unknown)=>setData(current=>({...current,[key]:value} as Data));
 const products=rows.filter(r=>r.kind==='products'&&r.data.status==='active');
 const updateItem=(index:number,patch:Partial<ProformaItem>)=>setData(d=>({...d,items:d.items.map((item,i)=>i===index?{...item,...patch}:item)}));
 const addItem=()=>{const p=products[0];if(!p)return toast.error('ابتدا یک محصول فعال در کاتالوگ ثبت کنید.');setData(d=>({...d,items:[...d.items,{product_id:p.id,name:p.data.name,unit:p.data.unit,quantity:1,unit_price:p.data.price}]}));};
 const totals=quoteAmounts(data),title=editing.intent==='lead'?'سرنخ':labels[kind];
 function submit(e:FormEvent){e.preventDefault();const parsed=dataSchema.safeParse(data);if(!parsed.success)return toast.error(parsed.error.issues[0].message);const error=validateSales(kind,parsed.data);if(error)return toast.error(error);if(kind==='proformas'&&!parent)return toast.error('مشتری پیش‌فاکتور را انتخاب کنید.');onSave(parsed.data,parent||null);}
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent dir="rtl" className={'editor-dialog '+(kind==='proformas'?'quote-editor':'')}><DialogTitle>{editing.row?'ویرایش':'ثبت'} {title}</DialogTitle><DialogDescription>{kind==='proformas'?'اقلام، تعداد و مبلغ را بررسی کنید. تمام مبالغ به تومان است.':'اطلاعات را وارد کنید و ذخیره را بزنید.'}</DialogDescription>
 <form className="form-grid" onSubmit={submit}>
 <BusinessFields kind={kind} data={data} set={set}/>
 <label className="full">{kind==='contacts'?'نام و نام خانوادگی':kind==='tasks'?'عنوان پیگیری':kind==='proformas'?'عنوان پیش‌فاکتور':kind==='automations'?'نام قانون':'نام / عنوان'}<Input autoFocus required maxLength={160} value={data.name} onChange={e=>set('name',e.target.value)}/></label>
 {['contacts','deals','tasks','proformas'].includes(kind)&&<label className="full">مشتری مرتبط<Pick label="مشتری مرتبط" value={parent} onChange={setParent} options={[{value:'',label:kind==='proformas'?'انتخاب مشتری':'بدون مشتری'},...rows.filter(r=>r.kind==='companies').map(r=>({value:r.id,label:r.data.name}))]}/></label>}
 {kind==='activities'&&<label className="full">مرتبط با<Pick label="رکورد مرتبط" value={parent} onChange={setParent} options={[{value:'',label:'بدون ارتباط'},...rows.filter(r=>['companies','contacts','deals'].includes(r.kind)).map(r=>({value:r.id,label:`${r.data.name} · ${labels[r.kind]}`}))]}/></label>}
 {(kind==='companies'||kind==='contacts')&&<><label>ایمیل<Input type="email" dir="ltr" value={data.email} onChange={e=>set('email',e.target.value)}/></label><label>تلفن<Input dir="ltr" maxLength={50} value={data.phone} onChange={e=>set('phone',e.target.value)}/></label><label>{kind==='companies'?'حوزهٔ فعالیت':'سمت'}<Input maxLength={100} value={kind==='companies'?data.industry:data.position} onChange={e=>set(kind==='companies'?'industry':'position',e.target.value)}/></label><label>شهر<Input maxLength={100} value={data.city} onChange={e=>set('city',e.target.value)}/></label><label>وضعیت<Pick label="وضعیت" value={data.status} onChange={v=>set('status',v)} options={[{value:'active',label:'مشتری فعال'},{value:'lead',label:'سرنخ'},{value:'inactive',label:'غیرفعال'}]}/></label></>}
 {kind==='products'&&<><label>کد محصول (SKU)<Input dir="ltr" maxLength={80} value={data.sku} onChange={e=>set('sku',e.target.value)}/></label><label>دسته‌بندی<Input maxLength={100} value={data.category} onChange={e=>set('category',e.target.value)}/></label><label>واحد فروش<Input required maxLength={30} placeholder="عدد، کیلوگرم، لیتر…" value={data.unit} onChange={e=>set('unit',e.target.value)}/></label><label>قیمت فروش (تومان)<Input type="number" dir="ltr" min={0} max={1e15} step="1" value={data.price} onChange={e=>set('price',Number(e.target.value))}/></label><label>{editing.row?'موجودی فعلی':'موجودی اولیه'}<Input type="number" dir="ltr" readOnly={!!editing.row} min={0} max={1e12} step="0.01" value={data.stock} onChange={e=>set('stock',Number(e.target.value))}/>{editing.row&&<small>تغییر موجودی از بخش انبارداری</small>}</label><label>حداقل موجودی<Input type="number" dir="ltr" min={0} max={1e12} step="0.01" value={data.min_stock} onChange={e=>set('min_stock',Number(e.target.value))}/></label><label>وضعیت<Pick label="وضعیت محصول" value={data.status} onChange={v=>set('status',v)} options={[{value:'active',label:'فعال'},{value:'inactive',label:'غیرفعال'}]}/></label></>}
 {kind==='proformas'&&<><label>شمارهٔ پیش‌فاکتور<Input required dir="ltr" maxLength={80} value={data.quote_number} onChange={e=>set('quote_number',e.target.value)}/></label><label>وضعیت<Pick label="وضعیت پیش‌فاکتور" value={data.quote_status} onChange={v=>set('quote_status',v)} options={Object.entries(quoteStatusLabels).map(([value,label])=>({value,label}))}/></label><label>پایان اعتبار<PersianDateInput value={data.valid_until} onChange={v=>set('valid_until',v)} ariaLabel="تاریخ اعتبار پیش‌فاکتور به شمسی"/></label><div className="full quote-line-editor"><div className="section-title"><h3><Package size={18}/> اقلام پیش‌فاکتور</h3><Button variant="outline" type="button" disabled={data.items.length>=100} onClick={addItem}><Plus size={16}/>افزودن محصول</Button></div><div className="quote-line-head"><span>محصول</span><span>تعداد</span><span>قیمت واحد</span><span>جمع</span><span/></div>{data.items.map((item,index)=><div className="quote-line" key={index}><div><Pick label={'محصول ردیف '+(index+1)} value={item.product_id} onChange={id=>{const p=products.find(r=>r.id===id);if(p)updateItem(index,{product_id:id,name:p.data.name,unit:p.data.unit,unit_price:p.data.price});}} options={[...products.map(p=>({value:p.id,label:p.data.name})),...(!products.some(p=>p.id===item.product_id)?[{value:item.product_id,label:item.name+' (بایگانی‌شده)'}]:[])]}/><small>{item.unit||'عدد'}</small></div><Input aria-label={'تعداد ردیف '+(index+1)} required type="number" min="0.01" max={1e6} step="0.01" value={item.quantity} onChange={e=>updateItem(index,{quantity:Number(e.target.value)})}/><Input aria-label={'قیمت واحد ردیف '+(index+1)} required type="number" min={0} max={1e15} step="1" value={item.unit_price} onChange={e=>updateItem(index,{unit_price:Number(e.target.value)})}/><strong>{num(totals.lines[index])}</strong><Button variant="ghost" size="icon" type="button" aria-label={'حذف ردیف '+(index+1)} onClick={()=>set('items',data.items.filter((_,i)=>i!==index))}><Trash2 size={16}/></Button></div>)}{!data.items.length&&<p className="muted">برای شروع یک محصول اضافه کنید.</p>}</div><label>تخفیف (درصد)<Input type="number" dir="ltr" min={0} max={100} step="0.01" value={data.discount_percent} onChange={e=>set('discount_percent',Number(e.target.value))}/></label><label>مالیات (درصد)<Input type="number" dir="ltr" min={0} max={100} step="0.01" value={data.tax_percent} onChange={e=>set('tax_percent',Number(e.target.value))}/></label><div className="full quote-summary"><span>جمع اقلام <b>{money(totals.subtotal)}</b></span><span>تخفیف <b>{money(totals.discount)}</b></span><span>مالیات <b>{money(totals.tax)}</b></span><strong>مبلغ نهایی <b>{money(totals.total)}</b></strong></div></>}
 {kind==='automations'&&<><label>زمان اجرا<Pick label="محرک قانون" value={data.automation_trigger} onChange={v=>set('automation_trigger',v)} options={Object.entries(automationTriggerLabels).map(([value,label])=>({value,label}))}/></label><label>اقدام<Pick label="اقدام قانون" value={data.automation_action} onChange={v=>set('automation_action',v)} options={Object.entries(automationActionLabels).map(([value,label])=>({value,label}))}/></label>{data.automation_trigger==='stage_change'&&<label>مرحلهٔ مقصد<Pick label="مرحله مقصد" value={data.automation_stage} onChange={v=>set('automation_stage',v)} options={stages.map(value=>({value,label:stageLabels[value]}))}/></label>}<label>{data.automation_trigger==='quote_expiry'?'چند روز پیش از پایان اعتبار':'موعد پیگیری چند روز بعد باشد؟'}<Input type="number" min={0} max={365} step="1" value={data.automation_days} onChange={e=>set('automation_days',Number(e.target.value))}/></label><label>وضعیت قانون<Pick label="وضعیت قانون" value={data.automation_enabled&&data.status==='active'?'active':'inactive'} onChange={v=>setData(d=>({...d,status:v as Data['status'],automation_enabled:v==='active'}))} options={[{value:'active',label:'فعال'},{value:'inactive',label:'غیرفعال'}]}/></label><p className="muted full">در نسخهٔ ویندوز، قانون‌ها هنگام بازبودن برنامه و در شروع اجرای بعدی بررسی می‌شوند.</p></>}
 {kind==='deals'&&<><label>مبلغ فرصت (تومان)<DealAmount value={data.amount} onChange={value=>set('amount',value)}/></label><label>مرحلهٔ فروش<Pick label="مرحله فروش" value={data.stage} onChange={v=>set('stage',v)} options={stages.map(value=>({value,label:stageLabels[value]}))}/></label></>}
 {(kind==='deals'||kind==='tasks'||kind==='activities')&&<><label>{kind==='activities'?'تاریخ فعالیت':'موعد'}<PersianDateInput value={data.due} onChange={v=>set('due',v)} ariaLabel="موعد به شمسی"/><DealDue value={data.due}/></label><label>مسئول<Pick label="مسئول" value={data.assignee} onChange={v=>set('assignee',v)} options={[{value:'',label:'تعیین نشده'},...members.map(m=>({value:m.user_id,label:m.email}))]}/></label></>}
 {kind==='activities'&&<><label>نوع فعالیت<Pick label="نوع فعالیت" value={data.activity_type} onChange={v=>set('activity_type',v)} options={Object.entries(activityTypeLabels).map(([value,label])=>({value,label}))}/></label><label>جهت<Pick label="جهت فعالیت" value={data.activity_direction} onChange={v=>set('activity_direction',v)} options={Object.entries(activityDirectionLabels).map(([value,label])=>({value,label}))}/></label><label>ساعت شروع<Input type="time" dir="ltr" value={data.activity_time} onChange={e=>set('activity_time',e.target.value)}/></label><label>ساعت پایان<Input type="time" dir="ltr" value={data.activity_end_time} onChange={e=>set('activity_end_time',e.target.value)}/></label><label className="full">محل / لینک جلسه<Input maxLength={300} value={data.activity_location} onChange={e=>set('activity_location',e.target.value)}/></label><label className="full">نتیجه فعالیت<Input maxLength={500} value={data.activity_result} onChange={e=>set('activity_result',e.target.value)}/></label></>}
 {['tasks','activities'].includes(kind)&&<><label>اولویت<Pick label="اولویت" value={data.priority} onChange={v=>set('priority',v)} options={Object.entries(priorityLabels).map(([value,label])=>({value,label}))}/></label><label>وضعیت<Pick label={kind==='activities'?'وضعیت فعالیت':'وضعیت پیگیری'} value={data.status} onChange={v=>set('status',v)} options={[{value:'open',label:'باز'},{value:'done',label:'انجام‌شده'}]}/></label></>}
 <label className="full">{kind==='automations'?'متن پیگیری یا یادآوری':'توضیحات'}<Textarea rows={3} maxLength={10000} value={data.description} onChange={e=>set('description',e.target.value)}/></label><div className="row full form-actions"><Button disabled={busy} type="submit" className="primary">{busy?'در حال ذخیره…':'ذخیره اطلاعات'}</Button><Button type="button" variant="outline" disabled={busy} onClick={onClose}>انصراف</Button></div>
 </form></DialogContent></Dialog>;
}
