'use client';
import {useState,type FormEvent} from 'react';
import {Boxes,PackagePlus,PackageMinus,History,TriangleAlert,SlidersHorizontal,Download} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {type Row} from '@/lib/crm';
import {NoRows,num,money,date} from './shared';
export type InventoryInput={product_id:string;type:'in'|'out'|'adjustment';quantity:number;version:number;reference:string;description:string};
const movementNames={in:'ورود کالا',out:'خروج کالا',adjustment:'اصلاح شمارش',opening:'موجودی اولیه'};
export function Inventory({rows,query,filter,busy,canEdit,onMovement,onOpen,onExport}:{rows:Row[];query:string;filter:string;busy:boolean;canEdit:boolean;onMovement:(input:InventoryInput)=>Promise<boolean>;onOpen:(id:string)=>void;onExport:(rows:Row[])=>void}){
 const [movement,setMovement]=useState<{product:Row;type:InventoryInput['type']}|null>(null);
 const products=rows.filter(r=>r.kind==='products'),active=products.filter(r=>r.data.status==='active'),low=active.filter(r=>r.data.stock<=r.data.min_stock);
 const shown=products.filter(r=>(filter!=='low'||r.data.stock<=r.data.min_stock)&&[r.data.name,r.data.sku,r.data.category].join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 const ledger=rows.filter(r=>r.kind==='stock_movements'&&[r.data.name,r.data.movement_reference,r.data.description].join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 return <><section className="inventory-metrics"><article><Boxes/><span>محصول فعال</span><b>{num(active.length)}</b></article><article><TriangleAlert/><span>نیاز به تأمین</span><b>{num(low.length)}</b></article><article><PackageMinus/><span>ناموجود</span><b>{num(active.filter(r=>r.data.stock===0).length)}</b></article><article><History/><span>ارزش موجودی با قیمت فروش</span><b>{money(products.reduce((s,r)=>s+r.data.stock*r.data.price,0))}</b></article></section>
 <Tabs dir="rtl" defaultValue="stock"><TabsList className="inventory-tabs"><TabsTrigger value="stock">موجودی کالاها</TabsTrigger><TabsTrigger value="ledger">گردش انبار <span>{num(ledger.length)}</span></TabsTrigger></TabsList><TabsContent value="stock"><article className="panel records-panel">{shown.length?<Table><TableHeader><TableRow><TableHead>محصول / کد</TableHead><TableHead>موجودی</TableHead><TableHead>حداقل موجودی</TableHead><TableHead>وضعیت</TableHead><TableHead>عملیات انبار</TableHead></TableRow></TableHeader><TableBody>{shown.map(p=><TableRow key={p.id}><TableCell><button className="name-cell" onClick={()=>onOpen(p.id)}><span className="company-avatar"><Boxes size={19}/></span><span>{p.data.name}<small dir="ltr">{p.data.sku||'—'}</small></span></button></TableCell><TableCell><strong>{num(p.data.stock)}</strong> {p.data.unit}</TableCell><TableCell>{num(p.data.min_stock)} {p.data.unit}</TableCell><TableCell><span className={'badge '+(p.data.status==='inactive'?'inactive':p.data.stock<=p.data.min_stock?'rejected':'active')}>{p.data.status==='inactive'?'غیرفعال':p.data.stock===0?'ناموجود':p.data.stock<=p.data.min_stock?'نیاز به تأمین':'کافی'}</span></TableCell><TableCell>{canEdit&&<div className="row wrap">{p.data.status==='active'&&<><Button variant="outline" disabled={busy} onClick={()=>setMovement({product:p,type:'in'})}><PackagePlus size={15}/>ورود</Button><Button variant="outline" disabled={busy||p.data.stock===0} onClick={()=>setMovement({product:p,type:'out'})}><PackageMinus size={15}/>خروج</Button></>}<Button variant={p.data.status==='inactive'?'outline':'ghost'} aria-label={'اصلاح موجودی '+p.data.name} disabled={busy||(p.data.status==='inactive'&&p.data.stock===0)} onClick={()=>setMovement({product:p,type:'adjustment'})}><SlidersHorizontal size={16}/>{p.data.status==='inactive'&&p.data.stock>0?'صفر کردن موجودی':null}</Button></div>}</TableCell></TableRow>)}</TableBody></Table>:<NoRows title="محصولی برای نمایش نیست" description="محصول را در کاتالوگ ثبت کنید یا فیلتر را تغییر دهید."/>}</article></TabsContent>
 <TabsContent value="ledger"><article className="panel"><div className="section-title"><div><h2>سابقهٔ ورود و خروج کالا</h2><p>برای اصلاح اشتباه، عملیات جدید ثبت کنید؛ سابقه حذف نمی‌شود.</p></div><Button variant="outline" onClick={()=>onExport(ledger)}><Download size={16}/>Excel گردش انبار</Button></div>{ledger.length?<Table><TableHeader><TableRow><TableHead>محصول</TableHead><TableHead>نوع</TableHead><TableHead>تغییر موجودی</TableHead><TableHead>مانده</TableHead><TableHead>تاریخ</TableHead><TableHead>مرجع / توضیح</TableHead></TableRow></TableHeader><TableBody>{ledger.map(r=><TableRow key={r.id}><TableCell>{r.data.name}</TableCell><TableCell>{movementNames[r.data.movement_type]}</TableCell><TableCell><span className={'badge '+(r.data.movement_quantity>0?'active':'rejected')} dir="ltr">{r.data.movement_quantity>0?'+':''}{num(r.data.movement_quantity)}</span></TableCell><TableCell>{num(r.data.stock_after)} {r.data.unit}</TableCell><TableCell>{date(r.created_at)}</TableCell><TableCell>{r.data.movement_reference||'—'}<small className="block muted">{r.data.description}</small></TableCell></TableRow>)}</TableBody></Table>:<NoRows title="گردشی ثبت نشده است" description="اولین ورود یا خروج کالا را ثبت کنید."/>}</article></TabsContent></Tabs>
 {movement&&<MovementDialog product={rows.find(r=>r.id===movement.product.id)||movement.product} type={movement.type} busy={busy} onClose={()=>setMovement(null)} onSave={async input=>{if(await onMovement(input))setMovement(null);}}/>}</>;
}
function MovementDialog({product,type,busy,onClose,onSave}:{product:Row;type:InventoryInput['type'];busy:boolean;onClose:()=>void;onSave:(input:InventoryInput)=>void}){
 const [quantity,setQuantity]=useState(type==='adjustment'?(product.data.status==='inactive'?0:product.data.stock):1),[reference,setReference]=useState(''),[description,setDescription]=useState('');
 const after=type==='adjustment'?quantity:Math.round((product.data.stock+(type==='in'?quantity:-quantity))*100)/100;
 const invalid=quantity<0||(type!=='adjustment'&&quantity===0)||after<0||after===product.data.stock;
 const submit=(e:FormEvent)=>{e.preventDefault();onSave({product_id:product.id,version:product.version,type,quantity,reference,description});};
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent dir="rtl" className="editor-dialog"><DialogTitle>{movementNames[type]} · {product.data.name}</DialogTitle><DialogDescription>{product.data.status==='inactive'&&type==='adjustment'?'محصول غیرفعال است؛ فقط اصلاح موجودی به صفر مجاز است. ':''}موجودی فعلی: {num(product.data.stock)} {product.data.unit}</DialogDescription><form className="form-grid" onSubmit={submit}><label>{type==='adjustment'?'موجودی شمارش‌شده':'مقدار '+movementNames[type]}<Input autoFocus required type="number" dir="ltr" min={type==='adjustment'?0:0.01} max={type==='out'?product.data.stock:1e12} step="0.01" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><label>مرجع (اختیاری)<Input maxLength={160} placeholder="شمارهٔ رسید یا پیش‌فاکتور" value={reference} onChange={e=>setReference(e.target.value)}/></label><label className="full">توضیح{type==='adjustment'?' (الزامی)':''}<Textarea required={type==='adjustment'} maxLength={10000} value={description} onChange={e=>setDescription(e.target.value)}/></label><div className={'full movement-preview '+(after<0?'error':'')}><span>موجودی پس از ثبت</span><b>{num(after)} {product.data.unit}</b></div><div className="row full"><Button disabled={busy||invalid} type="submit" className="primary">{busy?'در حال ثبت…':'تأیید و ثبت '+movementNames[type]}</Button><Button disabled={busy} type="button" variant="outline" onClick={onClose}>انصراف</Button></div></form></DialogContent></Dialog>;
}
