'use client';
import {NumberInput} from '@/components/ui/number-input';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Pick,PersianDateInput,date,num} from './shared';
import {localDay,type Row} from '@/lib/crm';
type Event={id:string;step:string;note:string;date:string;quantity:number;reference:string};
type ReturnRow={id:string;customer_id:string;product_id:string;quantity:number;return_date:string;created_at:string;reason:string;reference:string;material_type:string;sor_number:string;status:'pending'|'received'|'rejected';restocked:boolean;version:number;material_condition:string;batch_number:string;thinner_batch:string;workflow:{stage:string;events:Event[]}};
async function request(body?:unknown){const r=await fetch('/api/returns',{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'عملیات انجام نشد.');return d;}
const materialTypes:Record<string,string>={paint:'رنگ',primer:'آستر',clearcoat:'کیلر',other:'سایر'};
const statuses={pending:'در انتظار دریافت',received:'دریافت‌شده',rejected:'ردشده'};
const steps:Record<string,string>={inspection:'بررسی فنی',rework:'اصلاح مواد',ready:'آماده ارسال',resend:'ارسال مجدد',resent:'ارسال کامل',note:'یادداشت پیگیری'};
const conditions:Record<string,string>={raw:'خام',thinned:'تینرخورده',unknown:'ثبت نشده'};
const clean=(s:string)=>s.trim().toLowerCase().replace(/ي/g,'ی').replace(/ك/g,'ک').replace(/[۰-۹]/g,c=>String(c.charCodeAt(0)-1776));
const emptyForm=()=>({customer_id:'',product_id:'',quantity:'',return_date:localDay(),reason:'',reference:'',material_type:'paint',sor_number:'',material_condition:'raw',batch_number:'',thinner_batch:''});
export function MaterialReturns({records,canEdit,onChanged}:{records:Row[];canEdit:boolean;onChanged:()=>Promise<void>}){
 const [rows,setRows]=useState<ReturnRow[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[editing,setEditing]=useState(false),[customerSearch,setCustomerSearch]=useState(''),[productSearch,setProductSearch]=useState('');
 const [deleting,setDeleting]=useState<string|null>(null);
 const [form,setForm]=useState(emptyForm),[active,setActive]=useState<string|null>(null);
 const [follow,setFollow]=useState({step:'inspection',note:'',day:localDay(),quantity:'',reference:''});
 const [confirm,setConfirm]=useState<{row:ReturnRow;decision:'received'|'rejected';restock:boolean}|null>(null);
 async function load(){const d=await request();setRows(d.rows);}
 useEffect(()=>{let live=true;request().then(d=>{if(live)setRows(d.rows);}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[]);
 const name=(id:string)=>records.find(r=>r.id===id)?.data.name||'رکورد مرتبط';
 const unit=(id:string)=>records.find(r=>r.id===id)?.data.unit||'';
 async function perform(body:unknown){if(busy)return false;setBusy(true);setError('');try{await request(body);await load();await onChanged();return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 const visible=rows.filter(r=>(filter==='all'||r.status===filter||(r.status==='received'&&r.workflow?.stage===filter))&&clean([name(r.customer_id),name(r.product_id),r.reference,r.sor_number,r.batch_number,r.thinner_batch,r.reason].join(' ')).includes(clean(query)));
 const batchRows=(r:ReturnRow,thinner=false)=>rows.filter(x=>(thinner||x.product_id===r.product_id)&&clean(thinner?x.thinner_batch||'':x.batch_number||'')===clean(thinner?r.thinner_batch:r.batch_number)).sort((a,b)=>a.created_at.localeCompare(b.created_at)||a.id.localeCompare(b.id));
 const field=(key:keyof ReturnType<typeof emptyForm>,value:string)=>setForm(f=>({...f,[key]:value}));
 return <section className="returns-workspace"><div className="section-title"><div><h2>پرونده‌های مواد برگشتی</h2><p className="muted">دریافت، بررسی و اصلاح مواد، سپس ارسال مجدد</p></div>{canEdit&&<Button className="return-create-button" onClick={()=>setEditing(v=>!v)}>{editing?'بستن فرم':'ثبت برگشت جدید'}</Button>}</div>{error&&<p role="alert" className="error">{error}</p>}
 {canEdit&&editing&&<form className="panel return-form" onSubmit={async e=>{e.preventDefault();if(await perform({action:'create',...form,quantity:Number(form.quantity)})){setForm(emptyForm());setEditing(false);}}}>
 <fieldset><legend>۱. مشتری و محصول</legend><div className="return-grid"><label>جست‌وجوی مشتری<Input value={customerSearch} onChange={e=>setCustomerSearch(e.target.value)} placeholder="نام مشتری…"/></label><label>جست‌وجوی محصول<Input value={productSearch} onChange={e=>setProductSearch(e.target.value)} placeholder="نام، کد محصول یا رال…"/></label><label>مشتری<Pick label="مشتری برگشت" value={form.customer_id} onChange={v=>field('customer_id',v)} options={[{value:'',label:'انتخاب مشتری'},...records.filter(r=>r.kind==='companies'&&(r.id===form.customer_id||clean(r.data.name).includes(clean(customerSearch)))).map(r=>({value:r.id,label:r.data.name}))]}/></label><label>محصول<Pick label="محصول برگشت" value={form.product_id} onChange={v=>setForm(f=>({...f,product_id:v,material_type:records.find(r=>r.id===v)?.data.product_type||'other'}))} options={[{value:'',label:'انتخاب محصول'},...records.filter(r=>r.kind==='products'&&(r.id===form.product_id||clean([r.data.name,r.data.sku,r.data.ral_code].join(' ')).includes(clean(productSearch)))).map(r=>({value:r.id,label:r.data.name+(r.data.archived?' (بایگانی)':'')}))]}/></label></div></fieldset>
 <fieldset><legend>۲. مشخصات مواد و بچ</legend><div className="return-grid"><label>نوع مواد<Pick label="نوع مواد برگشتی" value={form.material_type} onChange={v=>field('material_type',v)} options={Object.entries(materialTypes).map(([value,label])=>({value,label}))}/></label><label>حالت مواد<Pick label="حالت مواد برگشتی" value={form.material_condition} onChange={v=>setForm(f=>({...f,material_condition:v,thinner_batch:v==='raw'?'':f.thinner_batch}))} options={[{value:'raw',label:'خام'},{value:'thinned',label:'تینرخورده'}]}/></label><label>شماره بچ مواد<Input required dir="ltr" maxLength={80} value={form.batch_number} onChange={e=>field('batch_number',e.target.value)}/></label>{form.material_condition==='thinned'&&<label>شماره بچ تینر<Input required dir="ltr" maxLength={80} value={form.thinner_batch} onChange={e=>field('thinner_batch',e.target.value)}/></label>}<label>مقدار برگشتی {unit(form.product_id)&&'('+unit(form.product_id)+')'}<NumberInput required min="0.01" max="1000000000000" step="0.01" value={form.quantity} onChange={e=>field('quantity',e.target.value)}/></label></div>{form.batch_number.trim()&&<p className="muted">پرونده‌های قبلی همین محصول و بچ: {num(rows.filter(r=>r.product_id===form.product_id&&clean(r.batch_number||'')===clean(form.batch_number)).length)}</p>}</fieldset>
 <fieldset><legend>۳. اطلاعات برگشت</legend><div className="return-grid"><label>تاریخ برگشت<PersianDateInput value={form.return_date} onChange={v=>field('return_date',v)}/></label><label>شماره SOR<Input dir="ltr" maxLength={80} value={form.sor_number} onChange={e=>field('sor_number',e.target.value)}/></label><label>شماره فاکتور / مرجع<Input maxLength={160} value={form.reference} onChange={e=>field('reference',e.target.value)}/></label><label className="full">علت برگشت<Textarea required maxLength={2000} value={form.reason} onChange={e=>field('reason',e.target.value)}/></label></div></fieldset><Button disabled={busy||!form.customer_id||!form.product_id||!form.return_date} type="submit">ثبت پرونده برگشتی</Button></form>}
 <div className="toolbar"><Input aria-label="جست‌وجوی برگشتی‌ها" placeholder="مشتری، محصول، شماره بچ یا SOR…" value={query} onChange={e=>setQuery(e.target.value)}/><Pick label="وضعیت برگشتی" value={filter} onChange={setFilter} options={[{value:'all',label:'همه وضعیت‌ها'},...Object.entries(statuses).map(([value,label])=>({value,label})),...['inspection','rework','ready','resent'].map(value=>({value,label:steps[value]}))]}/></div>
 {loading?<p>در حال دریافت…</p>:visible.length?visible.map(r=>{const events=r.workflow?.events||[],sent=events.filter(e=>e.step==='resend').reduce((n,e)=>n+Number(e.quantity),0),remaining=Number(r.quantity)-sent;return <article className="panel return-card" key={r.id}><div className="section-title"><h3>{name(r.product_id)}</h3><span className="badge">{r.status==='received'?steps[r.workflow?.stage||'inspection']:statuses[r.status]}</span></div><dl className="return-facts"><div><dt>مشتری</dt><dd>{name(r.customer_id)}</dd></div><div><dt>مقدار / حالت</dt><dd>{num(Number(r.quantity))} {unit(r.product_id)} · {conditions[r.material_condition]||'ثبت نشده'}</dd></div><div><dt>بچ مواد</dt><dd><bdi>{r.batch_number||'ثبت نشده'}</bdi>{r.batch_number&&<small>نوبت ثبت {num(batchRows(r).findIndex(x=>x.id===r.id)+1)} از {num(batchRows(r).length)} پرونده این محصول و بچ</small>}</dd></div><div><dt>بچ تینر</dt><dd><bdi>{r.thinner_batch||'—'}</bdi>{r.thinner_batch&&<small>نوبت ثبت {num(batchRows(r,true).findIndex(x=>x.id===r.id)+1)} از {num(batchRows(r,true).length)} پرونده این بچ تینر</small>}</dd></div><div><dt>تاریخ / SOR</dt><dd>{date(r.return_date)} · <bdi>{r.sor_number||'—'}</bdi></dd></div><div><dt>مرجع / نوع</dt><dd>{r.reference||'—'} · {materialTypes[r.material_type]}</dd></div></dl><p className="return-note">{r.reason}</p>
 {r.status==='received'&&<p className="muted">{r.restocked?'دریافت در موجودی قابل‌استفاده':'دریافت در قرنطینه؛ خارج از موجودی قابل‌فروش'} · ارسال مجدد: {num(sent)} · باقی‌مانده: {num(remaining)} {unit(r.product_id)}</p>}
 {canEdit&&<div className="row wrap"><Button variant="outline" className="return-delete-button" disabled={busy} onClick={()=>setDeleting(deleting===r.id?null:r.id)}>حذف برگشتی</Button></div>}
 {deleting===r.id&&<div className="notice return-delete-confirm" role="alert"><strong>این پرونده برگشتی برای همیشه حذف شود؟</strong><p>مشخصات و تاریخچه اقدامات این پرونده حذف می‌شوند و از شمارش دفعات برگشت کنار می‌رود. موجودی و گردش‌های ثبت‌شدهٔ انبار تغییر نمی‌کنند. این کار قابل بازگشت نیست.</p><div className="row wrap"><Button className="return-delete-confirm-button" disabled={busy} onClick={async()=>{if(await perform({action:'delete',id:r.id,version:r.version})){setDeleting(null);if(active===r.id)setActive(null);if(confirm?.row.id===r.id)setConfirm(null);}}}>حذف دائمی پرونده</Button><Button variant="outline" disabled={busy} onClick={()=>setDeleting(null)}>انصراف</Button></div></div>}
 {canEdit&&r.status==='pending' &&<div className="row wrap"><Button disabled={busy} onClick={()=>setConfirm({row:r,decision:'received',restock:false})}>دریافت در قرنطینه</Button><Button variant="outline" disabled={busy||r.material_condition==='thinned'} onClick={()=>setConfirm({row:r,decision:'received',restock:true})}>دریافت قابل‌استفاده در انبار</Button><Button variant="outline" disabled={busy} onClick={()=>setConfirm({row:r,decision:'rejected',restock:false})}>رد برگشت</Button></div>}
 {confirm?.row.id===r.id&&<div className="notice"><p>{confirm.restock?'مواد خام به موجودی قابل‌فروش اضافه شود؟':confirm.decision==='rejected'?'برگشت رد شود؟':'دریافت در قرنطینه، بدون افزایش موجودی قابل‌فروش ثبت شود؟'}</p><Button disabled={busy} onClick={async()=>{if(await perform({action:'resolve',id:r.id,version:r.version,decision:confirm.decision,restock:confirm.restock}))setConfirm(null);}}>تأیید دریافت / تصمیم</Button><Button variant="ghost" onClick={()=>setConfirm(null)}>انصراف</Button></div>}
 {events.length>0&&<details><summary>تاریخچه اقدامات و ارسال‌ها ({num(events.length)})</summary><ol className="return-history">{events.map(e=><li key={e.id}><b>{steps[e.step]} · {date(e.date)}</b><p className="return-note">{e.note}</p>{e.step==='resend'&&<p>{num(Number(e.quantity))} {unit(r.product_id)} · حواله: <bdi>{e.reference}</bdi></p>}</li>)}</ol></details>}
 {canEdit&&r.status==='received'&&<Button variant="outline" disabled={busy} onClick={()=>{setActive(active===r.id?null:r.id);setFollow({step:remaining>0?'inspection':'note',note:'',day:localDay(),quantity:'',reference:''});}}>ثبت اقدام / ارسال مجدد</Button>}
 {active===r.id&&<form className="return-followup return-grid" onSubmit={async e=>{e.preventDefault();if(await perform({action:'followup',id:r.id,version:r.version,...follow,quantity:follow.step==='resend'?Number(follow.quantity):0}))setActive(null);}}><label>اقدام<Pick label="اقدام برگشتی" value={follow.step} onChange={v=>setFollow({...follow,step:v})} options={(remaining>0?['inspection','rework','ready',...(r.workflow?.stage==='ready'?['resend']:[]),'note']:['note']).map(value=>({value,label:steps[value]}))}/></label><label>تاریخ اقدام<PersianDateInput value={follow.day} onChange={v=>setFollow({...follow,day:v})}/></label><label className="full">شرح بررسی، اصلاح یا نتیجه<Textarea required maxLength={2000} value={follow.note} onChange={e=>setFollow({...follow,note:e.target.value})}/></label>{follow.step==='resend'&&<><label>مقدار ارسال مجدد ({unit(r.product_id)})<NumberInput required min="0.01" max={remaining} step="0.01" value={follow.quantity} onChange={e=>setFollow({...follow,quantity:e.target.value})}/></label><label>شماره حواله ارسال<Input required maxLength={160} value={follow.reference} onChange={e=>setFollow({...follow,reference:e.target.value})}/></label><p className="full muted">{r.restocked?'با ثبت، خروج از موجودی انبار هم انجام می‌شود؛ جداگانه خروج ثبت نکنید.':'ارسال از قرنطینه ثبت می‌شود؛ موجودی قابل‌فروش تغییر نمی‌کند.'}</p></>}<Button disabled={busy} type="submit">ثبت اقدام</Button><Button type="button" variant="ghost" onClick={()=>setActive(null)}>انصراف</Button></form>}
 </article>;}):<p>پرونده‌ای با این فیلتر وجود ندارد.</p>}</section>;
}
