'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Pick,PersianDateInput,date,num} from './shared';
import {localDay,type Row} from '@/lib/crm';
type ReturnRow={id:string;customer_id:string;product_id:string;quantity:number;return_date:string;reason:string;reference:string;material_type:string;sor_number:string;status:'pending'|'received'|'rejected';restocked:boolean;version:number};
async function request(body?:unknown){const r=await fetch('/api/returns',{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'عملیات انجام نشد.');return d;}
const materialTypes:Record<string,string>={paint:'رنگ',primer:'آستر',clearcoat:'کیلر',other:'سایر'};
const statuses={pending:'در انتظار رسیدگی',received:'دریافت‌شده',rejected:'ردشده'};
export function MaterialReturns({records,canEdit,onChanged}:{records:Row[];canEdit:boolean;onChanged:()=>Promise<void>}){
 const [rows,setRows]=useState<ReturnRow[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[filter,setFilter]=useState('all'),[query,setQuery]=useState('');
 const [form,setForm]=useState({customer_id:'',product_id:'',quantity:'',return_date:localDay(),reason:'',reference:'',material_type:'paint',sor_number:''});
 const [confirm,setConfirm]=useState<{row:ReturnRow;decision:'received'|'rejected';restock:boolean}|null>(null);
 async function load(){const d=await request();setRows(d.rows);}
 useEffect(()=>{let active=true;request().then(d=>{if(active)setRows(d.rows);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
 const name=(id:string)=>records.find(r=>r.id===id)?.data.name||'رکورد مرتبط';
 async function perform(body:unknown){if(busy)return false;setBusy(true);setError('');try{await request(body);await load();await onChanged();return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 const visible=rows.filter(r=>(filter==='all'||r.status===filter)&&[name(r.customer_id),name(r.product_id),r.reference,r.sor_number,materialTypes[r.material_type],r.reason].join(' ').includes(query));
 return <section className="panel"><h2>مواد برگشتی</h2><p className="settings-copy">ثبت برگشت موجودی را تغییر نمی‌دهد. پس از دریافت، مواد قابل‌استفاده را به انبار اضافه کنید؛ مواد معیوب را بدون افزایش موجودی ثبت کنید.</p>{error&&<p role="alert" className="error">{error}</p>}{canEdit&&<form className="form-grid" onSubmit={async e=>{e.preventDefault();if(await perform({action:'create',...form,quantity:Number(form.quantity)}))setForm({...form,quantity:'',reason:'',reference:'',sor_number:''});}}><label>مشتری<Pick label="مشتری برگشت" value={form.customer_id} onChange={v=>setForm({...form,customer_id:v})} options={[{value:'',label:'انتخاب مشتری'},...records.filter(r=>r.kind==='companies').map(r=>({value:r.id,label:r.data.name}))]}/></label><label>محصول<Pick label="محصول برگشت" value={form.product_id} onChange={v=>setForm({...form,product_id:v})} options={[{value:'',label:'انتخاب محصول'},...records.filter(r=>r.kind==='products').map(r=>({value:r.id,label:r.data.name+' · '+r.data.unit}))]}/></label><label>نوع مواد<Pick label="نوع مواد برگشتی" value={form.material_type} onChange={v=>setForm({...form,material_type:v})} options={Object.entries(materialTypes).map(([value,label])=>({value,label}))}/></label><label>شماره SOR<Input dir="ltr" maxLength={80} value={form.sor_number} onChange={e=>setForm({...form,sor_number:e.target.value})}/></label><label>مقدار مواد برگشتی<Input required type="number" min="0.01" max="1000000000000" step="0.01" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/></label><label>تاریخ برگشت<PersianDateInput value={form.return_date} onChange={v=>setForm({...form,return_date:v})}/></label><label>شماره فاکتور / مرجع<Input maxLength={160} value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></label><label className="full">علت برگشت<Textarea required maxLength={2000} value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label><Button disabled={busy||!form.customer_id||!form.product_id||!form.return_date} type="submit">ثبت مواد برگشتی</Button></form>}
 <div className="toolbar"><Input aria-label="جست‌وجوی برگشتی‌ها" placeholder="مشتری، محصول، نوع مواد یا SOR…" value={query} onChange={e=>setQuery(e.target.value)}/><Pick label="وضعیت برگشتی" value={filter} onChange={setFilter} options={[{value:'all',label:'همه وضعیت‌ها'},...Object.entries(statuses).map(([value,label])=>({value,label}))]}/></div>
 {loading?<p>در حال دریافت…</p>:visible.length?visible.map(r=><article className="duplicate-card" key={r.id}><h3>{name(r.product_id)} · {num(Number(r.quantity))} {records.find(p=>p.id===r.product_id)?.data.unit}</h3><p>{materialTypes[r.material_type]||'سایر'} · SOR: <b dir="ltr">{r.sor_number||'—'}</b></p><p>{name(r.customer_id)} · {date(r.return_date)} · {statuses[r.status]}</p><p style={{whiteSpace:'pre-wrap'}}>{r.reason}</p>{r.reference&&<p>مرجع: {r.reference}</p>}{r.status==='received'&&<p>{r.restocked?'به موجودی قابل‌استفاده اضافه شد':'دریافت شد؛ بدون افزایش موجودی قابل‌استفاده'}</p>}{canEdit&&r.status==='pending'&&<div className="row wrap"><Button disabled={busy} onClick={()=>setConfirm({row:r,decision:'received',restock:true})}>دریافت و افزودن به انبار</Button><Button variant="outline" disabled={busy} onClick={()=>setConfirm({row:r,decision:'received',restock:false})}>دریافت مواد معیوب / قرنطینه</Button><Button variant="outline" disabled={busy} onClick={()=>setConfirm({row:r,decision:'rejected',restock:false})}>رد برگشت</Button></div>}{confirm?.row.id===r.id&&<div className="notice" role="alert"><p>{confirm.restock?'مقدار '+num(Number(r.quantity))+' به موجودی اضافه شود؟':confirm.decision==='rejected'?'برگشت رد شود؟':'دریافت بدون افزایش موجودی ثبت شود؟'} این رسید پس از تأیید نهایی می‌شود.</p><Button disabled={busy} onClick={async()=>{if(await perform({action:'resolve',id:r.id,version:r.version,decision:confirm.decision,restock:confirm.restock}))setConfirm(null);}}>تأیید نهایی</Button><Button variant="ghost" disabled={busy} onClick={()=>setConfirm(null)}>انصراف</Button></div>}</article>):<p>برگشتی ثبت‌شده‌ای با این فیلتر وجود ندارد.</p>}</section>;
}
