'use client';
import {DealDue} from './deal-fields';
import {useState} from 'react';
import {Building2,GripVertical,Plus,ArrowUpLeft} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {stages,stageLabels,type Row,type Data} from '@/lib/crm';
import {Pick,money,num} from './shared';
export function Pipeline({rows,allRows,busy,canEdit,onOpen,onMove,onNew}:{rows:Row[];allRows:Row[];busy:boolean;canEdit:boolean;onOpen:(id:string)=>void;onMove:(row:Row,stage:Data['stage'])=>void;onNew:()=>void}){
 const [dragging,setDragging]=useState<string|null>(null),[over,setOver]=useState('');
 return <><div className="pipeline-intro"><span>{num(rows.length)} فرصت · {money(rows.reduce((s,r)=>s+r.data.amount,0))}</span><small>کارت را بین مرحله‌ها بکشید یا مرحله را از فهرست داخل کارت انتخاب کنید.</small></div><section className="kanban kanban-v5">{stages.map(stage=>{const list=rows.filter(r=>r.data.stage===stage);return <article key={stage} className={'kanban-column stage-'+stage+(over===stage?' drop-target':'')} onDragOver={e=>{if(canEdit&&!busy&&dragging){e.preventDefault();setOver(stage);}}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setOver('');}} onDrop={e=>{e.preventDefault();const row=rows.find(r=>r.id===dragging);setOver('');setDragging(null);if(row&&canEdit&&!busy&&row.data.stage!==stage)onMove(row,stage);}}><header><h2><span className={'stage-marker stage-'+stage}/>{stageLabels[stage]}</h2><span className="count">{num(list.length)}</span></header><p className="column-sum">{money(list.reduce((s,r)=>s+r.data.amount,0))}</p>{list.map(r=><div className={'deal-card '+(dragging===r.id?'dragging':'')} key={r.id} draggable={canEdit&&!busy} onDragStart={e=>{setDragging(r.id);e.dataTransfer.setData('text/plain',r.id);e.dataTransfer.effectAllowed='move';}} onDragEnd={()=>{setDragging(null);setOver('');}}><div className="deal-heading"><button className="card-title" onClick={()=>onOpen(r.id)}>{r.data.name}</button>{canEdit&&<GripVertical size={16}/>}</div><p><Building2 size={14}/>{allRows.find(p=>p.id===r.parent_id)?.data.name||'بدون مشتری'}</p><strong>{money(r.data.amount)}</strong><div className="deal-card-footer"><DealDue value={r.data.due} closed={r.data.stage==='won'||r.data.stage==='lost'}/><Button size="icon" variant="ghost" aria-label={'پرونده '+r.data.name} onClick={()=>onOpen(r.id)}><ArrowUpLeft size={16}/></Button></div>{canEdit&&!busy?<Pick label={'مرحلهٔ '+r.data.name} value={r.data.stage} onChange={s=>onMove(r,s as Data['stage'])} options={stages.map(value=>({value,label:stageLabels[value]}))}/>:<span className="muted">{stageLabels[r.data.stage]}</span>}</div>)}{!list.length&&<p className="column-empty">فرصتی در این مرحله نیست</p>}{stage==='lead'&&canEdit&&<Button className="column-add" variant="ghost" onClick={onNew}><Plus size={16}/>فرصت جدید</Button>}</article>;})}</section></>;
}
