'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {PersianDateInput,roleLabels} from './shared';
type User={id:string;email:string;created_at:string;confirmed:boolean;disabled:boolean;expires_on:string|null;owner:boolean;workspaces:{name:string;role:'admin'|'sales'|'viewer'}[]};
async function request(body?:unknown){const r=await fetch('/api/admin',{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'اطلاعات مدیریت خوانده نشد.');return d;}
function AccessRow({user,onSaved}:{user:User;onSaved:()=>Promise<void>}){const [disabled,setDisabled]=useState(user.disabled),[expires,setExpires]=useState(user.expires_on||''),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');return <article className="duplicate-card"><h3 dir="ltr">{user.email}</h3><p>{user.owner?'مالک نرم‌افزار':user.confirmed?'ایمیل تأییدشده':'در انتظار تأیید ایمیل'}</p><p>{user.workspaces.map(w=>w.name+' ('+roleLabels[w.role]+')').join('، ')||'هنوز فضای کاری نساخته است'}</p>{user.owner?<p className="muted">دسترسی مالک قابل تعلیق نیست.</p>:<><div className="advanced-filters"><label>پایان اعتبار (خالی: نامحدود)<PersianDateInput value={expires} onChange={v=>{setExpires(v);setReview(false);}} ariaLabel={'پایان اعتبار '+user.email}/></label><label><input type="checkbox" checked={disabled} onChange={e=>{setDisabled(e.target.checked);setReview(false);}}/> تعلیق دسترسی</label><Button variant="outline" disabled={busy} onClick={()=>setReview(true)}>بررسی تغییر</Button></div>{review&&<div className="notice"><p>وضعیت جدید: {disabled?'معلق':'فعال'}؛ پایان اعتبار: {expires||'نامحدود'}. اطلاعات کاربر حذف نمی‌شود.</p><Button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await request({user_id:user.id,disabled,expires_on:expires||null});await onSaved();setReview(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>تأیید تغییر دسترسی</Button><Button variant="ghost" onClick={()=>setReview(false)}>انصراف</Button></div>}</>}{error&&<p role="alert" className="error">{error}</p>}</article>;}
export function PlatformAdmin(){const [users,setUsers]=useState<User[]>([]),[query,setQuery]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true);async function reload(){try{const d=await request();setUsers(d.users);setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}}useEffect(()=>{void reload();},[]);return <section className="panel"><h2>مدیریت کاربران آنلاین</h2><p className="settings-copy">فعال‌سازی، تعلیق و پایان اعتبار کاربران. این تنظیمات دسترسی آنلاین را کنترل می‌کنند؛ نسخهٔ کاملاً آفلاین از این پنل کنترل نمی‌شود. پایان اعتبار شامل روز انتخاب‌شده بر مبنای زمان سرور است.</p><Input aria-label="جست‌وجوی کاربران" placeholder="جست‌وجوی ایمیل یا شرکت…" value={query} onChange={e=>setQuery(e.target.value)}/>{loading&&<p>در حال دریافت…</p>}{error&&<p role="alert" className="error">{error}<Button variant="outline" onClick={reload}>تلاش دوباره</Button></p>}{users.filter(u=>(u.email+' '+u.workspaces.map(w=>w.name).join(' ')).toLowerCase().includes(query.toLowerCase())).map(u=><AccessRow key={u.id+u.disabled+u.expires_on} user={u} onSaved={reload}/>)}</section>;}
