'use client';
import {ArrowUpLeft,Check,Package,Zap} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {labels,statusLabels,stageLabels,quoteStatusLabels,quoteAmounts,automationTriggerLabels,automationActionLabels,type Row} from '@/lib/crm';
import {NoRows,num,money,date,priorityLabels} from './shared';
export function Records({rows,allRows,view,busy,canEdit,onOpen,onToggle}:{rows:Row[];allRows:Row[];view:string;busy:boolean;canEdit:boolean;onOpen:(id:string)=>void;onToggle:(r:Row)=>void}){
 if(!rows.length)return <article className="panel"><NoRows title="موردی برای نمایش نیست" description="یک مورد ثبت کنید یا جست‌وجو و فیلتر را تغییر دهید."/></article>;
 if(view==='automations')return <section className="rule-grid">{rows.map(r=><article className="panel rule-card" key={r.id}><div className="section-title"><span className="action-icon"><Zap size={20}/></span><span className={'badge '+(r.data.automation_enabled&&r.data.status==='active'?'active':'inactive')}>{r.data.automation_enabled&&r.data.status==='active'?'فعال':'غیرفعال'}</span></div><button onClick={()=>onOpen(r.id)}><h2>{r.data.name}</h2></button><div className="rule-step"><span>وقتی</span><b>{automationTriggerLabels[r.data.automation_trigger]}</b></div><div className="rule-step"><span>انجام شود</span><b>{automationActionLabels[r.data.automation_action]}</b></div><p>{r.data.description||'بدون توضیح'}</p><Button variant="outline" onClick={()=>onOpen(r.id)}>جزئیات قانون <ArrowUpLeft size={16}/></Button></article>)}</section>;
 const headers=view==='products'?['محصول / کد','دسته‌بندی','قیمت واحد','موجودی','وضعیت']:view==='proformas'?['پیش‌فاکتور','مشتری','مبلغ نهایی','اعتبار تا','وضعیت']:view==='tasks'?['عنوان پیگیری','مشتری','موعد','اولویت','وضعیت']:view==='contacts'?['نام مخاطب','مشتری مرتبط','اطلاعات تماس','سمت (عنوان شغلی)','وضعیت']:view==='leads'||view==='companies'?['نام','حوزهٔ فعالیت','اطلاعات تماس','آدرس','وضعیت']:['عنوان','مشتری مرتبط','اطلاعات تماس','مرحلهٔ فروش','وضعیت'];
 return <article className="panel records-panel"><Table><TableHeader><TableRow><TableHead>ردیف</TableHead>{headers.map(h=><TableHead key={h}>{h}</TableHead>)}<TableHead><span className="sr-only">عملیات</span></TableHead></TableRow></TableHeader><TableBody>{rows.map((r,index)=><TableRow key={r.id}><TableCell>{num(index+1)}</TableCell><TableCell><button className="name-cell" onClick={()=>onOpen(r.id)}><span className="company-avatar">{view==='products'?<Package size={18}/>:r.data.name[0]}</span><span>{r.data.name}<small>{view==='proformas'?r.data.quote_number:view==='products'?r.data.sku:date(r.created_at)}</small></span></button></TableCell><TableCell>{view==='products'?r.data.category||'—':view==='companies'||view==='leads'?r.data.industry||'—':allRows.find(p=>p.id===r.parent_id)?.data.name||'بدون مشتری'}</TableCell><TableCell>{view==='products'?money(r.data.price):view==='proformas'?money(quoteAmounts(r.data).total):view==='tasks'?date(r.data.due):<span className="contact-info" dir="ltr">{r.data.phone||r.data.email||'—'}</span>}</TableCell><TableCell>{view==='products'?num(r.data.stock)+' '+r.data.unit:view==='proformas'?date(r.data.valid_until):view==='tasks'?<span className={'priority '+r.data.priority}>{priorityLabels[r.data.priority]}</span>:view==='contacts'?r.data.position||'—':view==='companies'||view==='leads'?r.data.address||'—':view==='deals'?stageLabels[r.data.stage]||'—':r.data.city||'—'}</TableCell><TableCell><span className={'badge '+(view==='proformas'?r.data.quote_status:r.data.status)}>{view==='proformas'?quoteStatusLabels[r.data.quote_status]:statusLabels[r.data.status]}</span></TableCell><TableCell><div className="row">{canEdit&&view==='tasks'&&<Button variant="ghost" size="icon" disabled={busy} aria-label={'تغییر وضعیت '+r.data.name} onClick={()=>onToggle(r)}><Check size={17}/></Button>}<Button size="icon" variant="ghost" onClick={()=>onOpen(r.id)} aria-label={'جزئیات '+(labels[r.kind]||'')+' '+r.data.name}><ArrowUpLeft size={17}/></Button></div></TableCell></TableRow>)}</TableBody></Table></article>;
}
