'use client';
import {ArrowUpLeft,Check,Package,Zap,Phone,CalendarDays,Mail,MessageSquare,MessageCircle,ClipboardList} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {labels,statusLabels,quoteStatusLabels,quoteAmounts,automationTriggerLabels,automationActionLabels,activityTypeLabels,activityDirectionLabels,type Row} from '@/lib/crm';
import {NoRows,num,money,date,priorityLabels} from './shared';
export function Records({rows,allRows,view,busy,canEdit,onOpen,onToggle}:{rows:Row[];allRows:Row[];view:string;busy:boolean;canEdit:boolean;onOpen:(id:string)=>void;onToggle:(r:Row)=>void}){
 if(!rows.length)return <article className="panel"><NoRows title="موردی برای نمایش نیست" description="یک مورد ثبت کنید یا جست‌وجو و فیلتر را تغییر دهید."/></article>;
 if(view==='automations')return <section className="rule-grid">{rows.map(r=><article className="panel rule-card" key={r.id}><div className="section-title"><span className="action-icon"><Zap size={20}/></span><span className={'badge '+(r.data.automation_enabled&&r.data.status==='active'?'active':'inactive')}>{r.data.automation_enabled&&r.data.status==='active'?'فعال':'غیرفعال'}</span></div><button onClick={()=>onOpen(r.id)}><h2>{r.data.name}</h2></button><div className="rule-step"><span>وقتی</span><b>{automationTriggerLabels[r.data.automation_trigger]}</b></div><div className="rule-step"><span>انجام شود</span><b>{automationActionLabels[r.data.automation_action]}</b></div><p>{r.data.description||'بدون توضیح'}</p><Button variant="outline" onClick={()=>onOpen(r.id)}>جزئیات قانون <ArrowUpLeft size={16}/></Button></article>)}</section>;
 const headers=view==='products'?['محصول / کد','دسته‌بندی','قیمت واحد','موجودی','وضعیت']:view==='proformas'?['پیش‌فاکتور','مشتری','مبلغ نهایی','اعتبار تا','وضعیت']:view==='activities'?['عنوان فعالیت','نوع','مرتبط با','زمان','وضعیت']:view==='tasks'?['عنوان پیگیری','مشتری','موعد','اولویت','وضعیت']:['نام','حوزه / مشتری مرتبط','اطلاعات تماس','شهر / سمت','وضعیت'];
 const activityIcon=(r:Row)=>{const t=r.kind==='tasks'?'task':r.data.activity_type;return t==='call'?<Phone size={17}/>:t==='meeting'?<CalendarDays size={17}/>:t==='email'?<Mail size={17}/>:t==='sms'?<MessageSquare size={17}/>:t==='whatsapp'?<MessageCircle size={17}/>:<ClipboardList size={17}/>;};
 return <article className="panel records-panel"><Table><TableHeader><TableRow><TableHead>ردیف</TableHead>{headers.map(h=><TableHead key={h}>{h}</TableHead>)}<TableHead><span className="sr-only">عملیات</span></TableHead></TableRow></TableHeader><TableBody>{rows.map((r,index)=><TableRow key={r.id}><TableCell>{num(index+1)}</TableCell><TableCell><button className="name-cell" onClick={()=>onOpen(r.id)}><span className="company-avatar">{view==='products'?<Package size={18}/>:view==='activities'?activityIcon(r):r.data.name[0]}</span><span>{r.data.name}<small>{view==='proformas'?r.data.quote_number:view==='products'?r.data.sku:date(r.created_at)}</small></span></button></TableCell><TableCell>{view==='products'?r.data.category||'—':view==='activities'?(r.kind==='tasks'?'وظیفه':activityTypeLabels[r.data.activity_type]):view==='companies'||view==='leads'?r.data.industry||'—':allRows.find(p=>p.id===r.parent_id)?.data.name||'بدون مشتری'}</TableCell><TableCell>{view==='products'?money(r.data.price):view==='proformas'?money(quoteAmounts(r.data).total):view==='activities'?(allRows.find(p=>p.id===r.parent_id)?.data.name||'بدون ارتباط'):view==='tasks'?date(r.data.due):<span className="contact-info" dir="ltr">{r.data.phone||r.data.email||'—'}</span>}</TableCell><TableCell>{view==='products'?num(r.data.stock)+' '+r.data.unit:view==='proformas'?date(r.data.valid_until):view==='activities'?<span>{date(r.data.due)}{r.kind==='activities'&&r.data.activity_time?<small className="activity-time"> · {r.data.activity_time}{r.data.activity_direction!=='none'?' · '+activityDirectionLabels[r.data.activity_direction]:''}</small>:null}</span>:view==='tasks'?<span className={'priority '+r.data.priority}>{priorityLabels[r.data.priority]}</span>:r.data.city||r.data.position||'—'}</TableCell><TableCell><span className={'badge '+(view==='proformas'?r.data.quote_status:r.data.status)}>{view==='proformas'?quoteStatusLabels[r.data.quote_status]:statusLabels[r.data.status]}</span></TableCell><TableCell><div className="row">{canEdit&&['tasks','activities'].includes(view)&&<Button variant="ghost" size="icon" disabled={busy} aria-label={'تغییر وضعیت '+r.data.name} onClick={()=>onToggle(r)}><Check size={17}/></Button>}<Button size="icon" variant="ghost" onClick={()=>onOpen(r.id)} aria-label={'جزئیات '+(labels[r.kind]||'')+' '+r.data.name}><ArrowUpLeft size={17}/></Button></div></TableCell></TableRow>)}</TableBody></Table></article>;
}
