'use client';
import {useEffect,useState} from 'react';
import {Pencil,RotateCcw,Trash2,Printer,FileSpreadsheet} from 'lucide-react';
import type {Row} from '@/lib/crm';
import {localDay} from '@/lib/crm';
import {materialLabels,resultLabels,defectLabels,defectName,newSample,newRound,newItem,sampleSchema,batchStats,itemKey,type SampleRow,type Round,type Item} from '@/lib/samples';
import {sampleReportHtml,sampleExcel,missingEnglish} from '@/lib/sample-report';
import styles from './samples.module.css';
import {PersianDateInput,date} from './shared';
async function api(body?:unknown){const r=await fetch('/api/samples',{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'درخواست ناموفق بود');return d;}
type Entry={key:string;row:SampleRow;round:Round|null};
const normalized=(list:SampleRow[])=>list.map(r=>({...r,data:sampleSchema.parse(r.data)}));
const customer=(e:Entry)=>e.round?.customer_name||e.row.data.details.customer_name?.en||e.row.data.details.customer_name?.fa||'';
const unitLabel=(u:string)=>({kg:'کیلوگرم',L:'لیتر',g:'گرم',mL:'میلی‌لیتر',piece:'عدد'}[u]||u);
const english=(s:string)=>!/[\u0600-\u06ff]/.test(s);
export function Samples({canEdit}:{records:Row[];canEdit:boolean}){
 const [rows,setRows]=useState<SampleRow[]>([]),[editor,setEditor]=useState<{row:SampleRow|null;round:Round}|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[selected,setSelected]=useState<string[]>([]),[deleting,setDeleting]=useState<Entry[]|null>(null),[defect,setDefect]=useState('');
 const reload=async()=>{setRows(normalized((await api()).rows));setSelected([]);};
 useEffect(()=>{let active=true;api().then(d=>{if(active)setRows(normalized(d.rows));}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return ()=>{active=false;};},[]);
 const entries:Entry[]=rows.flatMap<Entry>(row=>row.data.rounds.length?row.data.rounds.map(round=>({key:row.id+':'+round.id,row,round})):[{key:row.id,row,round:null}]);
 const visible=entries.filter(e=>(status==='all'||(e.round?.result||'pending')===status)&&[customer(e),...(e.round?.items||[]).flatMap(i=>[i.batch,i.description.en,i.description.fa,i.technical_number,i.sor])].join(' ').toLowerCase().includes(query.toLowerCase()));
 const stats=batchStats(rows),suggestions=[...new Set([...Object.keys(defectLabels).map(defectName),...rows.flatMap(s=>s.data.rounds.flatMap(r=>r.defects.map(defectName)))])];
 function open(e?:Entry,resend=false){let r=e?.round?structuredClone(e.round):{...newRound(),registration_date:localDay(),dispatch_date:localDay()};r.customer_name=e?customer(e):'';r.defects=r.defects.map(defectName);if(resend)r={...r,id:crypto.randomUUID(),registration_date:localDay(),dispatch_date:localDay(),result_date:'',return_date:'',production_date:'',result:'pending',defects:[],reason:{fa:'',en:''},action:{fa:'',en:''},comments:{fa:'',en:''},items:r.items.map(i=>({...i,outcome:'inherit',result:{fa:'',en:''}}))};setEditor({row:e?.row||null,round:r});setError('');setDefect('');}
 function update(patch:Partial<Round>){setEditor(e=>e?{...e,round:{...e.round,...patch}}:e);}
 function item(n:number,patch:Partial<Item>){setEditor(e=>{if(!e)return e;return {...e,round:{...e.round,items:e.round.items.map((i,j)=>{if(j!==n)return i;const v={...i,...patch};if(v.package_count!==null&&v.packing_weight!==null)v.quantity=Number((v.package_count*v.packing_weight).toFixed(6));return v;})}};});}
 async function save(){if(!editor||busy)return;const r={...editor.round,items:editor.round.items.map(i=>({...i,root_batch:i.root_batch||i.batch}))};if(!r.customer_name.trim()||!r.dispatch_date||r.items.some(i=>!i.batch.trim()||!i.description.en.trim())){setError('نام مشتری، تاریخ ارسال، شرح محصول و شماره بچ را وارد کنید.');return;}const texts=[r.customer_name,...r.defects,r.reason.en,r.action.en,r.comments.en,...r.items.flatMap(i=>[i.description.en,i.material_type_name,i.technical_number,i.batch,i.sor,i.result.en])];if(!texts.every(english)){setError('متن اطلاعات گزارش را به انگلیسی وارد کنید. سوابق قبلی محفوظ می‌مانند.');return;}const data=structuredClone(editor.row?.data||newSample());if(!editor.row){data.details.title={fa:'',en:r.customer_name};data.details.customer_name={fa:'',en:r.customer_name};}data.rounds=data.rounds.some(x=>x.id===r.id)?data.rounds.map(x=>x.id===r.id?r:x):[...data.rounds,r];const parsed=sampleSchema.safeParse(data);if(!parsed.success){setError(parsed.error.issues[0].message);return;}setBusy(true);setError('');try{await api({id:editor.row?.id||null,version:editor.row?.version||0,data:parsed.data});await reload();setEditor(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function remove(){if(!deleting||busy)return;const selections=Object.values(deleting.reduce<Record<string,{id:string;version:number;all:boolean;round_ids:string[]}>>((map,e)=>{const v=map[e.row.id]??={id:e.row.id,version:e.row.version,all:false,round_ids:[]};if(e.round)v.round_ids.push(e.round.id);else v.all=true;return map;},{}));setBusy(true);setError('');try{await api({action:'delete_many',selections});await reload();setDeleting(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function report(e:Entry,excel=false){if(!e.round)return;if(missingEnglish(e.row.data,[e.round])){setError('نام مشتری، شرح محصولات و یادداشت‌های انگلیسی این ارسال را تکمیل کنید.');return;}const html=sampleReportHtml(e.row.data,e.round,'en','results',rows);if(!english(html)){setError('پیش از خروجی گرفتن، متن انگلیسی همه فیلدهای گزارش را تکمیل کنید.');return;}setError('');if(!excel){const w=window.open('','_blank');if(!w){setError('برای باز شدن گزارش، اجازه نمایش پنجره جدید را در مرورگر بدهید.');return;}w.document.write(html);w.document.close();return;}setBusy(true);try{const bytes=await sampleExcel(e.row.data,e.round,'en','results',undefined,rows),url=URL.createObjectURL(new Blob([bytes.buffer as ArrayBuffer],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));const a=document.createElement('a');a.href=url;a.download='Sample-Dispatch-Report.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const r=editor?.round;
 return <section className={styles.workspace} dir="rtl" lang="fa"><header className={styles.toolbar}><div><h2>نمونه‌ها و آزمون مشتری</h2><p>سوابق ارسال نمونه، نتایج آزمون و سابقه بچ</p></div>{canEdit&&<button disabled={busy||loading} className={styles.primary} onClick={()=>open()}>+ ثبت ارسال جدید</button>}</header>
 {error&&<p role="alert" className={styles.error}>{error}</p>}
 {editor&&r?<form className={styles.form} onSubmit={e=>{e.preventDefault();void save();}}><div className={styles.toolbar}><h3>{editor.row?.data.rounds.some(x=>x.id===r.id)?'ویرایش ارسال':'ارسال جدید'}</h3><button type="button" disabled={busy} onClick={()=>setEditor(null)}>بستن</button></div><fieldset disabled={busy}><legend>مشخصات ارسال</legend><div className={styles.grid}><label>نام مشتری (انگلیسی)<input required value={r.customer_name} onChange={e=>update({customer_name:e.target.value})}/></label><label>تاریخ ثبت<PersianDateInput value={r.registration_date} onChange={value=>update({registration_date:value})}/></label><label>تاریخ ارسال<PersianDateInput value={r.dispatch_date} onChange={value=>update({dispatch_date:value})}/></label></div></fieldset>
 <datalist id="sample-material-options">{Object.values(materialLabels).map(l=><option key={l[1]} value={l[1]} label={l[0]}/>)}</datalist>
 {r.items.map((i,n)=><fieldset disabled={busy} key={n}><legend>محصول {n+1}</legend><div className={styles.grid}><label>شرح محصول (انگلیسی)<input required value={i.description.en} onChange={e=>item(n,{description:{...i.description,en:e.target.value}})}/>{i.description.fa&&<small dir="auto">مقدار قبلی: {i.description.fa}</small>}</label><label>نوع ماده (انگلیسی)<input list="sample-material-options" value={i.material_type_name} placeholder="انتخاب یا وارد کردن نوع ماده" onChange={e=>item(n,{material_type_name:e.target.value})}/></label><label>کد محصول<input value={i.technical_number} onChange={e=>item(n,{technical_number:e.target.value})}/></label><label>شماره بچ<input required value={i.batch} onChange={e=>item(n,{batch:e.target.value})}/></label><label>تاریخ تولید<PersianDateInput value={i.manufacture_date} onChange={value=>item(n,{manufacture_date:value})}/></label><label>شماره SOR<input value={i.sor} onChange={e=>item(n,{sor:e.target.value})}/></label><label>تعداد بسته<input type="number" min="1" step="1" value={i.package_count??''} onFocus={e=>e.target.select()} onChange={e=>item(n,{package_count:e.target.value===''?null:Number(e.target.value)})}/></label><label>مقدار هر بسته<input type="number" min="0.000001" step="any" value={i.packing_weight??''} onFocus={e=>e.target.select()} onChange={e=>item(n,{packing_weight:e.target.value===''?null:Number(e.target.value)})}/></label><label>واحد<select value={i.unit} onChange={e=>item(n,{unit:e.target.value as Item['unit']})}>{['kg','L','g','mL','piece'].map(u=><option key={u} value={u}>{unitLabel(u)}</option>)}</select></label><label>مقدار کل{i.package_count!==null&&i.packing_weight!==null?<output>{i.quantity.toLocaleString('fa-IR',{maximumFractionDigits:6})} {unitLabel(i.unit)}</output>:<input required type="number" min="0.000001" step="any" value={i.quantity||''} onFocus={e=>e.target.select()} onChange={e=>item(n,{quantity:Number(e.target.value)})}/>}</label><label>نتیجه محصول (اختیاری)<select value={i.outcome} onChange={e=>item(n,{outcome:e.target.value as Item['outcome']})}><option value="inherit">مطابق نتیجه کلی</option><option value="pending">در انتظار نتیجه</option><option value="approved">تأییدشده</option><option value="rejected">ردشده</option></select></label><label>مشاهدات محصول (انگلیسی)<input value={i.result.en} onChange={e=>item(n,{result:{...i.result,en:e.target.value}})}/></label></div><button type="button" disabled={r.items.length===1} onClick={()=>update({items:r.items.filter((_,j)=>j!==n)})}>حذف محصول</button></fieldset>)}
 <button type="button" disabled={busy||r.items.length>=50} onClick={()=>update({items:[...r.items,newItem()]})}>+ افزودن محصول</button>
 <fieldset disabled={busy}><legend>نتیجه آزمون و پیگیری</legend><div className={styles.grid}><label>نتیجه کلی آزمون<select value={r.result} onChange={e=>update({result:e.target.value as Round['result']})}>{Object.entries(resultLabels).map(([v,l])=><option key={v} value={v}>{l[0]}</option>)}</select></label><label>تاریخ نتیجه<PersianDateInput value={r.result_date} onChange={value=>update({result_date:value})}/></label><label>تاریخ برگشت نمونه (در صورت برگشت)<PersianDateInput value={r.return_date} onChange={value=>update({return_date:value})}/></label>{r.result==='production'&&<label>تاریخ مصرف در تولید<PersianDateInput value={r.production_date} onChange={value=>update({production_date:value})}/></label>}</div><label>ایرادات</label><div className={styles.toolbar}><input list="sample-defect-options" aria-label="ایراد جدید" value={defect} placeholder="ایراد را به انگلیسی بنویسید و افزودن را بزنید" onChange={e=>setDefect(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();if(defect.trim()){update({defects:[...new Set([...r.defects,defect.trim()])]});setDefect('');}}}}/><button type="button" disabled={!defect.trim()||r.defects.length>=50} onClick={()=>{update({defects:[...new Set([...r.defects,defect.trim()])]});setDefect('');}}>افزودن ایراد</button></div><datalist id="sample-defect-options">{suggestions.map(d=><option key={d} value={d}/>)}</datalist><div className={styles.chips}>{r.defects.map(d=><button type="button" key={d} aria-label={'حذف '+d} onClick={()=>update({defects:r.defects.filter(x=>x!==d)})}>{d} ×</button>)}</div><div className={styles.grid}>{(['reason','action','comments'] as const).map((key,n)=><label key={key}>{['دلیل رد شدن (انگلیسی)','اقدام اصلاحی (انگلیسی)','بازخورد مشتری / توضیحات (انگلیسی)'][n]}<textarea rows={3} value={r[key].en} onChange={e=>update({[key]:{...r[key],en:e.target.value}})}/>{r[key].fa&&<small dir="auto">مقدار قبلی: {r[key].fa}</small>}</label>)}</div></fieldset>{error&&<p role="alert" className={styles.error}>{error}</p>}<footer className={styles.save}><button className={styles.primary} disabled={busy} type="submit">{busy?'در حال ذخیره…':'ثبت ارسال و نتیجه'}</button><button type="button" disabled={busy} onClick={()=>setEditor(null)}>انصراف</button></footer></form>:<>
 <div className={styles.toolbar}><input aria-label="جست‌وجوی نمونه‌ها" placeholder="جست‌وجوی مشتری، محصول، بچ یا SOR" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="فیلتر نتیجه" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">همه نتایج</option>{Object.entries(resultLabels).map(([v,l])=><option key={v} value={v}>{l[0]}</option>)}</select>{canEdit&&<><button disabled={busy||!selected.length} onClick={()=>setDeleting(entries.filter(e=>selected.includes(e.key)))}>حذف انتخاب‌شده‌ها ({selected.length})</button><button disabled={busy||!entries.length} onClick={()=>setDeleting(entries)}>حذف همه رکوردها</button></>}</div>
 {deleting&&<div className={styles.confirm} role="alertdialog" aria-label="تأیید حذف دائمی"><h3>آیا {deleting.length} رکورد انتخاب‌شده برای همیشه حذف شود؟</h3><p>نتایج و گزارش‌های این رکوردها نیز حذف می‌شوند. این کار قابل بازگشت نیست.</p><button className={styles.danger} disabled={busy} onClick={()=>void remove()}>تأیید حذف دائمی</button><button disabled={busy} onClick={()=>setDeleting(null)}>انصراف</button></div>}
 <div className={styles.table}><table><thead><tr>{canEdit&&<th><input aria-label="انتخاب همه رکوردهای نمایش‌داده‌شده" type="checkbox" checked={visible.length>0&&visible.every(e=>selected.includes(e.key))} onChange={e=>setSelected(e.target.checked?[...new Set([...selected,...visible.map(e=>e.key)])]:selected.filter(k=>!visible.some(e=>e.key===k)))}/></th>}<th>مشتری / ارسال</th><th>محصولات / بچ‌ها</th><th>نتیجه</th><th>دفعات رد / برگشت</th><th>عملیات</th></tr></thead><tbody>{visible.map(e=><tr key={e.key}>{canEdit&&<td><input aria-label={'انتخاب '+customer(e)} type="checkbox" checked={selected.includes(e.key)} onChange={ev=>setSelected(ev.target.checked?[...selected,e.key]:selected.filter(k=>k!==e.key))}/></td>}<td><strong>{customer(e)||'مشتری بدون نام'}</strong><small>{e.round?.dispatch_date?date(e.round.dispatch_date):'ارسالی ثبت نشده'}</small></td><td>{e.round?.items.map((i,n)=><div key={n}>{i.description.en||i.description.fa}<small>بچ {i.batch||'—'} · {i.quantity.toLocaleString('fa-IR')} {unitLabel(i.unit)}</small></div>)}</td><td><span className={styles.badge}>{resultLabels[e.round?.result||'pending'][0]}</span><small>{e.round?.result_date?date(e.round.result_date):''}</small></td><td>{e.round?.items.map((i,n)=>{const g=stats.find(g=>g.key===itemKey(i));return <small key={n}>بچ {i.batch||'—'}: <b>{g?.rejected||0}</b> بار رد · {g?.returned||0} بار برگشت</small>;})}</td><td><div className={styles.actions}>{canEdit&&<><button className={styles.edit} title="ویرایش و ثبت نتیجه" aria-label="ویرایش و ثبت نتیجه" disabled={busy} onClick={()=>open(e)}><Pencil size={17}/></button>{e.round&&<button className={styles.resend} title="ارسال مجدد" aria-label="ارسال مجدد" disabled={busy} onClick={()=>open(e,true)}><RotateCcw size={17}/></button>}<button className={styles.delete} title="حذف" aria-label="حذف" disabled={busy} onClick={()=>setDeleting([e])}><Trash2 size={17}/></button></>}{e.round&&<><button className={styles.print} title="چاپ گزارش" aria-label="چاپ گزارش" disabled={busy} onClick={()=>void report(e)}><Printer size={17}/></button><button className={styles.excel} title="خروجی اکسل" aria-label="خروجی اکسل" disabled={busy} onClick={()=>void report(e,true)}><FileSpreadsheet size={17}/></button></>}</div></td></tr>)}</tbody></table>{!visible.length&&<p>{loading?'در حال دریافت نمونه‌ها…':'نمونه‌ای یافت نشد.'}</p>}</div><p className={styles.hint}>هر آزمون ناموفق برای همان محصول و شماره بچ، یک بار رد شدن محسوب می‌شود. دفعات برگشت فیزیکی نمونه جداگانه شمارش می‌شود.</p></>}
 </section>;
}
