'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {type Row} from '@/lib/crm';
import {dailyWork,duplicatePairs} from '@/lib/workflow-tools';
import {date,num} from './shared';
export function Followups({rows,onOpen,onNew}:{rows:Row[];onOpen:(id:string)=>void;onNew?:(id:string)=>void}){const groups=dailyWork(rows);return <div className="workflow-grid">{([['today','پیگیری‌های امروز'],['overdue','پیگیری‌های عقب‌افتاده'],['undated','پیگیری‌های بدون تاریخ'],['neglected','مشتریان بدون ارتباط در ۳۰ روز اخیر']] as const).map(([key,title])=><section className="panel" key={key}><h2>{title} <small>{num(groups[key].length)}</small></h2>{groups[key].length?groups[key].map(r=><div className="workflow-row" key={r.id}><button onClick={()=>onOpen(r.id)}><b>{r.data.name}</b><small>{key==='neglected'?'بدون فعالیت تکمیل‌شده در ۳۰ روز اخیر':r.data.due?date(r.data.due):'زمان پیگیری تعیین نشده'} · {rows.find(x=>x.id===r.parent_id)?.data.name||''}</small></button>{key==='neglected'&&onNew&&<Button variant="outline" onClick={()=>onNew(r.id)}>ثبت پیگیری</Button>}</div>):<p className="muted">موردی وجود ندارد.</p>}</section>)}</div>;}
export function Duplicates({rows,onOpen,onMerge,busy}:{rows:Row[];onOpen:(id:string)=>void;onMerge?:(a:Row,b:Row)=>void;busy:boolean}){const pairs=duplicatePairs(rows);const [selected,setSelected]=useState<string>('');return <section className="panel"><h2>بررسی موارد مشابه · {num(pairs.length)}</h2><p className="settings-copy">شباهت نام، تلفن یا ایمیل به معنی تکراری‌بودن قطعی نیست. رکورد اصلی را خودتان انتخاب کنید. در ادغام، اطلاعات رکورد دوم و اختلاف‌ها به‌صورت یادداشت حفظ می‌شوند و ارتباط‌ها منتقل می‌شوند.</p>{pairs.map(({a,b,reasons})=><div className="duplicate-card" key={a.id+b.id}><span className="badge">شباهت در {reasons.join('، ')}</span>{[a,b].map(r=><div className="workflow-row" key={r.id}><button onClick={()=>onOpen(r.id)}><b>{r.data.name}</b><small>{r.data.phone} · {r.data.email} · {r.data.city}</small></button>{onMerge&&<Button disabled={busy} variant="outline" onClick={()=>setSelected(a.id+b.id+r.id)}>انتخاب به‌عنوان اصلی</Button>}</div>)}{onMerge&&[a,b].some(r=>selected===a.id+b.id+r.id)&&<div className="notice"><p>رکورد اصلی: <b>{selected===a.id+b.id+a.id?a.data.name:b.data.name}</b>. رکورد دوم پس از انتقال ارتباط‌ها و حفظ کامل اطلاعات در یادداشت ادغام، حذف می‌شود.</p><Button disabled={busy} onClick={()=>{const keep=selected===a.id+b.id+a.id?a:b;onMerge(keep,keep.id===a.id?b:a);setSelected('');}}>تأیید ادغام</Button><Button variant="ghost" onClick={()=>setSelected('')}>انصراف</Button></div>}</div>)}{!pairs.length&&<p className="muted">مورد مشابهی پیدا نشد.</p>}</section>;}
export function BackupStatus(){const [status,setStatus]=useState<{count:number;last:string|null}>(),[error,setError]=useState('');useEffect(()=>{window.peyvand?.backupStatus().then(setStatus).catch(()=>setError('وضعیت پشتیبان خوانده نشد.'));},[]);return <div className="notice"><b>پشتیبان خودکار فعال است</b><p>روزی یک بار هنگام اجرای برنامه و پیش از ذخیره، حذف و ادغام، پشتیبان جداگانه نگهداری می‌شود. پشتیبان‌های قبلی خودکار حذف نمی‌شوند.</p>{status&&<p>{num(status.count)} فایل · آخرین پشتیبان: {status.last?new Date(status.last).toLocaleString('fa-IR'):'هنوز ساخته نشده'}</p>}{error&&<p role="alert">{error}</p>}<Button variant="outline" onClick={()=>window.peyvand?.backupFolder().catch(()=>setError('پوشه پشتیبان باز نشد.'))}>باز کردن پوشه پشتیبان‌ها</Button></div>;}
