import {quoteAmounts,quoteStatusLabels,type Row} from './crm';
const amount=(n:number)=>new Intl.NumberFormat('fa-IR').format(n);
const faDate=(s:string)=>s?new Intl.DateTimeFormat('fa-IR',{dateStyle:'medium'}).format(new Date(s.length===10?s+'T12:00:00':s)):'تعیین نشده';
const safe=(v:unknown)=>String(v??'').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('\"','&quot;').replaceAll("'",'&#39;');
export function proformaHtml(row: Row, rows: Row[], organization: string) {
    const data = row.data, totals = quoteAmounts(data), customer = rows.find(r => r.id === row.parent_id);
    const lines = data.items.map((item, i) => `<tr><td>${amount(i+1)}</td><td>${safe(item.name)}</td><td>${safe(item.unit || 'عدد')}</td><td class="number">${amount(item.quantity)}</td><td class="number">${amount(item.unit_price)}</td><td class="number">${amount(totals.lines[i])}</td></tr>`).join('');
    return `<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><title>${safe(data.quote_number || data.name)}</title><style>
    @font-face{font-family:Vazirmatn;src:url('/fonts/vazirmatn-arabic.woff2') format('woff2');font-weight:100 900;font-display:block}
    @page{size:A4;margin:15mm 13mm}*{box-sizing:border-box}body{margin:0;color:#203e36;font-family:Vazirmatn,Tahoma,Arial,sans-serif;font-size:11pt;line-height:1.85}
    header{display:flex;justify-content:space-between;border-bottom:3px solid #175747;padding-bottom:15px;margin-bottom:20px}h1{font-size:26pt;line-height:1.4;margin:0 0 4px}h2{font-size:13pt;margin:0}.muted{color:#586f67;font-size:10pt}.meta{text-align:left}.meta b{display:block;font-size:13pt}.info{padding:12px 15px;background:#f1f6f3;border:1px solid #d7e3dc;margin:16px 0;overflow-wrap:anywhere}.info p{margin:2px 0}.info b{margin-left:5px}
    table{border-collapse:collapse;width:100%;table-layout:fixed;margin:18px 0}thead{display:table-header-group}th,td{border-bottom:1px solid #d5e0da;padding:9px 6px;text-align:right;vertical-align:top;overflow-wrap:anywhere}th{background:#175747;color:white;font-size:10pt;font-weight:600}th:first-child{width:7%}th:nth-child(2){width:31%}th:nth-child(3){width:9%}th:nth-child(4){width:10%}th:nth-child(5){width:21%}th:nth-child(6){width:22%}tbody tr:nth-child(even){background:#f6f9f7}tr{break-inside:avoid}.number{font-variant-numeric:tabular-nums;text-align:left;direction:rtl}
    .totals{width:65%;margin-right:auto;break-inside:avoid}.totals p{display:flex;justify-content:space-between;margin:0;padding:5px 10px;gap:20px}.totals .total{background:#e9f3ed;border-top:2px solid #175747;font-weight:700;font-size:13pt;margin-top:7px}.note{white-space:pre-wrap;overflow-wrap:anywhere;margin-top:20px;border-top:1px solid #d5e0da;padding-top:12px}.signatures{display:flex;justify-content:space-between;margin-top:30px;padding:18px 0 50px;break-inside:avoid;border-top:1px solid #d5e0da;color:#586f67}.footer{color:#697e74;font-size:9pt;text-align:center;margin-top:20px}*{-webkit-print-color-adjust:exact;print-color-adjust:exact}
    </style></head><body><header><div><h1>پیش‌فاکتور</h1><h2>${safe(organization)}</h2><div class="muted">${safe(data.name)}</div></div><div class="meta"><b dir="ltr">${safe(data.quote_number || 'بدون شماره')}</b><div>تاریخ صدور: ${safe(faDate(row.created_at))}</div><div>اعتبار تا: ${safe(faDate(data.valid_until))}</div><div class="muted">${safe(quoteStatusLabels[data.quote_status])}</div></div></header>
    <section class="info"><p><b>مشتری:</b>${safe(customer?.data.name || 'مشتری حذف شده یا تعیین نشده')}</p>${customer?.data.phone ? `<p><b>تلفن:</b><span dir="ltr">${safe(customer.data.phone)}</span></p>`:''}${customer?.data.city ? `<p><b>شهر:</b>${safe(customer.data.city)}</p>`:''}<p class="muted">تمام مبالغ به تومان است.</p></section>
    <table><thead><tr><th>ردیف</th><th>محصول / خدمت</th><th>واحد</th><th>تعداد</th><th>قیمت واحد</th><th>مبلغ ردیف</th></tr></thead><tbody>${lines}</tbody></table>
    <section class="totals"><p><span>جمع اقلام</span><b>${amount(totals.subtotal)}</b></p><p><span>تخفیف (${amount(data.discount_percent)}٪)</span><b>${amount(totals.discount)}</b></p><p><span>مالیات (${amount(data.tax_percent)}٪)</span><b>${amount(totals.tax)}</b></p><p class="total"><span>مبلغ نهایی</span><b>${amount(totals.total)} تومان</b></p></section>
    ${data.description?`<p class="note"><b>توضیحات:</b><br>${safe(data.description)}</p>`:''}<section class="signatures"><span>مهر و امضای فروشنده</span><span>تأیید خریدار</span></section><div class="footer">این سند پیش‌فاکتور است. ثبت خروج کالا در بخش انبارداری انجام می‌شود.</div></body></html>`;
}

