import {z} from 'zod';
const text=z.string().trim().max(4000).default('');
export const bilingual=z.object({fa:text,en:text});
export const fields={title:['عنوان پروژه','Project title'],requester:['درخواست‌کننده','Requester'],customer_name:['نام مشتری در گزارش','Customer name'],owner:['مسئول پیگیری','Follow-up owner'],substrate:['زیرآیند','Substrate'],preparation:['آماده‌سازی سطح','Surface preparation'],spray:['سیستم پاشش','Spray system'],layers:['ترتیب لایه‌ها','Order of layers'],drying:['روش خشک‌شدن / پخت','Drying / baking method'],temperature:['دمای پخت (°C)','Baking temperature (°C)'],time:['زمان پخت (دقیقه)','Baking time (min)'],color:['رنگ / رال','Colour / RAL'],mixing:['نسبت اختلاط و مبنای وزنی/حجمی','Mixing ratio and weight/volume basis'],customer_comments:['توضیحات مشتری','Customer comments'],technical_comments:['توضیحات فنی','Technical comments'],test_plan:['برنامه و معیار آزمون','Test plan and acceptance criteria'],copies:['گیرندگان رونوشت','Distribution of copies']} as const;
export type Field=keyof typeof fields;
export const materialLabels={primer:['آستر','Primer'],paint:['رنگ','Paint'],thinner:['تینر','Thinner'],hardener:['هاردنر','Hardener'],clear:['کیلر','Clearcoat'],other:['سایر','Other']} as const;
export const resultLabels={pending:['در انتظار نتیجه','Pending'],rejected:['رد','Rejected'],lab_approved:['تأیید آزمایشگاهی','Laboratory approved'],line_approved:['تأیید روی خط','Line approved'],production:['مصرف در تولید','Used in production']} as const;
export const defectLabels={pinhole:['سرسوزنی','Pinholing'],sagging:['شره','Sagging'],adhesion:['چسبندگی','Adhesion'],colour:['رنگ','Colour mismatch'],gloss:['براقیت','Gloss'],other:['سایر','Other']} as const;
const day=z.string().refine(s=>s===''||/^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s,'تاریخ نامعتبر');
export const itemSchema=z.object({product_id:z.string().uuid().or(z.literal('')),type:z.enum(['primer','paint','thinner','hardener','clear','other']),description:bilingual,grade:bilingual,technical_number:text,root_batch:text,batch:text,revision:z.number().int().min(0).max(9999),quantity:z.number().finite().positive().max(1e12),unit:z.enum(['kg','L','g','mL','piece']),viscosity:text,density:text,thickness:text,result:bilingual});
export const roundSchema=z.object({id:z.string().uuid(),dispatch_date:day,result_date:day,production_date:day,items:z.array(itemSchema).min(1).max(50),result:z.enum(['pending','rejected','lab_approved','line_approved','production']),defects:z.array(z.enum(['pinhole','sagging','adhesion','colour','gloss','other'])).max(6),reason:bilingual,action:bilingual,comments:bilingual,conditions:bilingual}).superRefine((r,c)=>{const err=(message:string)=>c.addIssue({code:'custom',message});if(r.result!=='pending'&&(!r.dispatch_date||!r.result_date))err('تاریخ ارسال و نتیجه الزامی است');if(r.result_date&&r.dispatch_date&&r.result_date<r.dispatch_date)err('نتیجه قبل از ارسال نیست');if(r.result==='rejected'&&(!r.defects.length||!(r.reason.fa||r.reason.en)))err('ایراد و علت رد را وارد کنید');if(r.result==='production'&&(!r.production_date||r.production_date<r.result_date))err('تاریخ مصرف باید پس از نتیجه باشد');if(r.result!=='pending'&&r.items.some(i=>!i.batch.trim()||!i.root_batch.trim()))err('شماره بچ اصلی و بچ آزمون را کامل کنید');if(r.items.some(i=>!(i.description.fa||i.description.en)))err('شرح هر قلم الزامی است');});
export const sampleSchema=z.object({customer_id:z.string().uuid(),return_id:z.string().uuid().or(z.literal('')).default(''),request_date:day,required_date:day,details:z.record(z.enum(Object.keys(fields) as [Field,...Field[]]),bilingual),rounds:z.array(roundSchema).max(200)}).superRefine((s,c)=>{if(!(s.details.title?.fa||s.details.title?.en))c.addIssue({code:'custom',message:'عنوان پرونده الزامی است'});if(new Set(s.rounds.map(r=>r.id)).size!==s.rounds.length)c.addIssue({code:'custom',message:'آزمون تکراری'});});
export type Sample=z.infer<typeof sampleSchema>;export type Round=z.infer<typeof roundSchema>;export type Item=z.infer<typeof itemSchema>;export type SampleRow={id:string;version:number;data:Sample};
export const pair=()=>({fa:'',en:''});
export const newItem=():Item=>({product_id:'',type:'paint',description:pair(),grade:pair(),technical_number:'',root_batch:'',batch:'',revision:0,quantity:1,unit:'kg',viscosity:'',density:'',thickness:'',result:pair()});
export const newRound=():Round=>({id:crypto.randomUUID(),dispatch_date:'',result_date:'',production_date:'',items:[newItem()],result:'pending',defects:[],reason:pair(),action:pair(),comments:pair(),conditions:pair()});
export const newSample=():Sample=>({customer_id:'',return_id:'',request_date:'',required_date:'',details:Object.fromEntries(Object.keys(fields).map(k=>[k,pair()])),rounds:[]});
export const normalizeBatch=(s:string)=>s.trim().toUpperCase().replace(/[۰-۹]/g,c=>String(c.charCodeAt(0)-1776)).replace(/[٠-٩]/g,c=>String(c.charCodeAt(0)-1632));
export function batchStats(samples:SampleRow[]){const groups=new Map<string,{batch:string;product:string;trials:Set<string>;rejected:Set<string>;defects:Map<string,Set<string>>}>();for(const s of samples)for(const r of s.data.rounds)for(const i of r.items){if(!i.root_batch)continue;const k=(i.product_id||i.technical_number||i.description.fa||i.description.en)+'|'+normalizeBatch(i.root_batch);let g=groups.get(k);if(!g){g={batch:i.root_batch,product:i.description.fa||i.description.en,trials:new Set(),rejected:new Set(),defects:new Map()};groups.set(k,g);}const id=s.id+':'+r.id;g.trials.add(id);if(r.result==='rejected'){g.rejected.add(id);for(const d of r.defects){if(!g.defects.has(d))g.defects.set(d,new Set());g.defects.get(d)!.add(id);}}}return [...groups.values()].map(g=>({batch:g.batch,product:g.product,trials:g.trials.size,rejected:g.rejected.size,defects:[...g.defects].map(([code,ids])=>({code,count:ids.size}))}));}
