import {z} from 'zod';
const text=z.string().trim().max(4000).default('');
export const bilingual=z.object({fa:text,en:text});
export const fields={title:['عنوان پروژه','Project title'],requester:['درخواست‌کننده','Requester'],customer_name:['نام مشتری در گزارش','Customer name'],owner:['مسئول پیگیری','Follow-up owner'],substrate:['زیرآیند','Substrate'],preparation:['آماده‌سازی سطح','Surface preparation'],spray:['سیستم پاشش','Spray system'],layers:['ترتیب لایه‌ها','Order of layers'],drying:['روش خشک‌شدن / پخت','Drying / baking method'],temperature:['دمای پخت (°C)','Baking temperature (°C)'],time:['زمان پخت (دقیقه)','Baking time (min)'],color:['رنگ / رال','Colour / RAL'],mixing:['نسبت اختلاط و مبنای وزنی/حجمی','Mixing ratio and weight/volume basis'],customer_comments:['توضیحات مشتری','Customer comments'],technical_comments:['توضیحات فنی','Technical comments'],test_plan:['برنامه و معیار آزمون','Test plan and acceptance criteria'],copies:['گیرندگان رونوشت','Distribution of copies']} as const;
export type Field=keyof typeof fields;
export const materialLabels={primer:['آستر','Primer'],paint:['رنگ','Paint'],thinner:['تینر','Thinner'],hardener:['هاردنر','Hardener'],clear:['کیلر','Clearcoat'],other:['سایر','Other']} as const;
export const resultLabels={pending:['در انتظار نتیجه','Pending'],rejected:['رد','Rejected'],lab_approved:['تأیید آزمایشگاهی','Laboratory approved'],line_approved:['تأیید روی خط','Line approved'],production:['مصرف در تولید','Used in production']} as const;
export const defectLabels={pinhole:['سرسوزنی','Pinholing'],sagging:['شره','Sagging'],adhesion:['چسبندگی','Adhesion'],colour:['رنگ','Colour mismatch'],gloss:['براقیت','Gloss'],other:['سایر','Other']} as const;
const day=z.string().refine(s=>s===''||/^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s,'Invalid date');
export const itemSchema=z.object({product_id:z.string().uuid().or(z.literal('')),type:z.enum(['primer','paint','thinner','hardener','clear','other']),material_type_name:text,description:bilingual,grade:bilingual,technical_number:text,root_batch:text,batch:text,revision:z.number().int().min(0).max(9999),quantity:z.number().finite().positive().max(1e12),unit:z.enum(['kg','L','g','mL','piece']),viscosity:text,density:text,thickness:text,outcome:z.enum(['inherit','pending','approved','rejected']).default('inherit'),result:bilingual,manufacture_date:day.default(''),package_count:z.number().int().positive().max(1000000000).nullable().default(null),packing_weight:z.number().finite().positive().max(1e12).nullable().default(null),sor:text});
export const roundSchema=z.object({id:z.string().uuid(),customer_name:text,registration_date:day.default(''),return_date:day.default(''),dispatch_date:day,result_date:day,production_date:day,items:z.array(itemSchema).min(1).max(50),result:z.enum(['pending','rejected','lab_approved','line_approved','production']),defects:z.array(z.string().trim().min(1).max(120)).max(50),reason:bilingual,action:bilingual,comments:bilingual,conditions:bilingual}).superRefine((r,c)=>{const err=(message:string)=>c.addIssue({code:'custom',message});if(r.return_date&&((r.result!=='rejected'&&!r.items.some(i=>i.outcome==='rejected'))||!r.result_date||r.return_date<r.result_date))err('A physical return requires a rejected result and cannot precede the result date.');for(const i of r.items){if((i.package_count===null)!==(i.packing_weight===null))err('Enter both package count and amount per package.');if(i.package_count!==null&&i.packing_weight!==null&&Math.abs(i.quantity-i.package_count*i.packing_weight)>0.000001)err('Total quantity must equal package count multiplied by amount per package.');}if((r.result!=='pending'||r.items.some(i=>i.outcome==='approved'||i.outcome==='rejected'))&&(!r.dispatch_date||!r.result_date))err('Dispatch and result dates are required.');if(r.result_date&&r.dispatch_date&&r.result_date<r.dispatch_date)err('Result date cannot precede dispatch.');if((r.result==='rejected'||r.items.some(i=>i.outcome==='rejected'))&&(!r.defects.length||!(r.reason.fa||r.reason.en)))err('Enter defects and failure reason.');if(r.result==='production'&&(!r.production_date||r.production_date<r.result_date))err('Production use date must be on or after the result date.');if(r.result!=='pending'&&r.items.some(i=>!i.batch.trim()||!i.root_batch.trim()))err('Enter the batch number.');if(r.items.some(i=>!(i.description.fa||i.description.en)))err('Every product requires a description.');});
export const sampleSchema=z.object({customer_id:z.string().uuid().or(z.literal('')),return_id:z.string().uuid().or(z.literal('')).default(''),request_date:day,required_date:day,details:z.record(z.enum(Object.keys(fields) as [Field,...Field[]]),bilingual),rounds:z.array(roundSchema).max(200)}).superRefine((s,c)=>{if(!(s.details.title?.fa||s.details.title?.en))c.addIssue({code:'custom',message:'Customer or record title is required.'});if(new Set(s.rounds.map(r=>r.id)).size!==s.rounds.length)c.addIssue({code:'custom',message:'Duplicate dispatch.'});});
export type Sample=z.infer<typeof sampleSchema>;export type Round=z.infer<typeof roundSchema>;export type Item=z.infer<typeof itemSchema>;export type SampleRow={id:string;version:number;data:Sample};
export const pair=()=>({fa:'',en:''});
export const newItem=():Item=>({product_id:'',type:'paint',outcome:'inherit',material_type_name:'',description:pair(),grade:pair(),technical_number:'',root_batch:'',batch:'',revision:0,quantity:1,unit:'kg',viscosity:'',density:'',thickness:'',result:pair(),manufacture_date:'',package_count:null,packing_weight:null,sor:''});
export const newRound=():Round=>({id:crypto.randomUUID(),customer_name:'',registration_date:'',return_date:'',dispatch_date:'',result_date:'',production_date:'',items:[newItem()],result:'pending',defects:[],reason:pair(),action:pair(),comments:pair(),conditions:pair()});
export const newSample=():Sample=>({customer_id:'',return_id:'',request_date:'',required_date:'',details:Object.fromEntries(Object.keys(fields).map(k=>[k,pair()])),rounds:[]});
export const normalizeBatch=(s:string)=>s.trim().toUpperCase().replace(/[۰-۹]/g,c=>String(c.charCodeAt(0)-1776)).replace(/[٠-٩]/g,c=>String(c.charCodeAt(0)-1632));
export const itemKey=(i:Item)=>(normalizeBatch(i.technical_number)||i.product_id||normalizeBatch(i.description.en||i.description.fa))+'|'+normalizeBatch(i.batch);
export function batchStats(samples:SampleRow[]){const groups=new Map<string,{key:string;batch:string;product:string;trials:Set<string>;rejected:Set<string>;returned:Set<string>;defects:Map<string,Set<string>>}>();for(const s of samples)for(const r of s.data.rounds)for(const i of r.items){if(!i.batch)continue;const k=itemKey(i);let g=groups.get(k);if(!g){g={key:k,batch:i.batch,product:i.description.fa||i.description.en,trials:new Set(),rejected:new Set(),returned:new Set(),defects:new Map()};groups.set(k,g);}const id=s.id+':'+r.id;g.trials.add(id);if(i.outcome==='rejected'||i.outcome==='inherit'&&r.result==='rejected'){g.rejected.add(id);if(r.return_date)g.returned.add(id);for(const d of r.defects){if(!g.defects.has(d))g.defects.set(d,new Set());g.defects.get(d)!.add(id);}}}return [...groups.values()].map(g=>({key:g.key,batch:g.batch,product:g.product,trials:g.trials.size,rejected:g.rejected.size,returned:g.returned.size,defects:[...g.defects].map(([code,ids])=>({code,count:ids.size}))}));}

export const defectName=(value:string)=>(defectLabels[value as keyof typeof defectLabels]?.[1]||value);
