import {resultLabels,defectName,batchStats,itemKey,type Sample,type Round,type SampleRow} from './samples';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function reportData(s:Sample,r:Round,_lang:'fa'|'en'='en',_kind:'request'|'results'='results',context?:SampleRow[]){
 const all=context||[{id:'current',version:1,data:s}],stats=batchStats(all),b=(p?:{fa:string;en:string})=>p?.en||'';
 const info=[['Date of Registration',r.registration_date||s.request_date],['Date of Send',r.dispatch_date],['Customer',r.customer_name||b(s.details.customer_name)]];
 const headers=['Row','Technical No','Description','Batch No','Number of occurrences','Production date','Unit','Number','Packing','Total Quantity','Product result','SOR'];
 const rows=r.items.map((i,n)=>[n+1,i.technical_number,b(i.description)+(i.material_type_name?' — '+i.material_type_name:''),i.batch,stats.find(g=>g.key===itemKey(i))?.rejected||0,i.manufacture_date||'',i.unit,i.package_count??'',i.packing_weight==null?'':`${i.packing_weight} ${i.unit}`,i.quantity,i.outcome==='inherit'?resultLabels[r.result][1]:i.outcome[0].toUpperCase()+i.outcome.slice(1),i.sor||'']);
 const notes=[['Test Result',resultLabels[r.result][1]],['Defects',r.defects.map(defectName).join(' / ')],['Failure Reason',b(r.reason)],['Corrective Action',b(r.action)],['Return Date',r.return_date||''],['Result Date',r.result_date],['Production Use Date',r.production_date],['Customer Comments',b(r.comments)],...r.items.filter(i=>i.result.en).map(i=>['Product observations — '+b(i.description),i.result.en])];
 const keys=new Set(r.items.map(itemKey));
 const history=all.flatMap(c=>c.data.rounds.flatMap(t=>t.items.filter(i=>keys.has(itemKey(i))).map(i=>[t.dispatch_date,t.customer_name||b(c.data.details.customer_name),b(i.description),i.batch,i.outcome==='inherit'?resultLabels[t.result][1]:i.outcome,t.defects.map(defectName).join(' / '),b(t.action),t.return_date]))).sort((a,b)=>a[0].localeCompare(b[0]));
 return {title:'Sample Dispatch',info,headers,rows,notes,history};
}
export function missingEnglish(s:Sample,rounds:Round[]){return rounds.some(r=>!(r.customer_name||s.details.customer_name?.en)?.trim()||r.items.some(i=>!i.description.en.trim())||[r.reason,r.action,r.comments].some(p=>p.fa&&!p.en.trim()));}
export function sampleReportHtml(s:Sample,r:Round,_lang:'fa'|'en'='en',_kind:'request'|'results'='results',context?:SampleRow[]){const x=reportData(s,r,'en','results',context);return `<!doctype html><html lang="en" dir="ltr"><head><meta charset="utf-8"><title>${x.title}</title><style>body{font:12px Arial,sans-serif;color:#193e49;margin:28px;line-height:1.5}header{border-bottom:4px solid #137489;background:#edf5f7;display:flex;align-items:center;justify-content:space-between;padding:22px;margin-bottom:18px}h1{font-size:20px;margin:0}.meta{display:flex;gap:24px;justify-content:space-between;margin:16px 0}.meta span{display:block;margin-top:8px;color:#164b76}table{border-collapse:collapse;width:100%;table-layout:fixed;margin:18px 0}th,td{border:1px solid #d3e0e5;padding:11px 6px;text-align:center;overflow-wrap:anywhere;white-space:pre-wrap}th{background:#163f4c;color:white;font-size:10px;letter-spacing:.2px}tbody tr:nth-child(even){background:#f4f8fa}th:first-child{width:30px}th:nth-child(3){width:13%}td{color:#164b76}thead{display:table-header-group}tr{break-inside:avoid}.notes th{width:20%;text-align:left;background:#edf4f6;color:#244d58}.notes{table-layout:auto}.notes td{min-height:32px}.foot{border-top:1px solid #cadbdf;padding-top:10px}.notes td{text-align:left}.foot{font-size:10px;color:#555}section{break-before:page}@page{size:A4 landscape;margin:12mm}@media print{button{display:none}body{margin:0;font-size:10px}h1{font-size:17px}}</style></head><body><button style="padding:10px 20px;margin-bottom:20px;background:#175c67;color:white;border:0;border-radius:6px;cursor:pointer" onclick="window.print()">Print / Save PDF</button><header><h1>${x.title}</h1><div><b>PEYVAND</b><br><small>CUSTOMER SAMPLE RECORD</small></div></header><div class="meta">${x.info.map(([k,v])=>`<div><b>${k}</b><span>${esc(v)}</span></div>`).join('')}</div><table><thead><tr>${x.headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${x.rows.map(row=>`<tr>${row.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table><p class="foot">Number of occurrences = rejected tests for this exact product and batch, including tests without a physical return. Total Quantity uses the unit shown in each row.</p><table class="notes">${x.notes.map(([k,v])=>`<tr><th>${k}</th><td>${esc(v)}</td></tr>`).join('')}</table>${x.history.length>1?`<section><h2>Batch Test History</h2><table class="history"><thead><tr>${['Dispatch date','Customer','Product','Batch','Result','Defects','Corrective action','Return date'].map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${x.history.map(row=>`<tr>${row.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></section>`:''}</body></html>`;}
export function sampleHistoryHtml(s:Sample,_lang:'fa'|'en'='en',context?:SampleRow[]){const pages=s.rounds.map(r=>sampleReportHtml(s,r,'en','results',context));return !pages.length?'':pages[0].replace('</body>',pages.slice(1).map(p=>'<section>'+p.slice(p.indexOf('<header>'),p.indexOf('</body>'))+'</section>').join('')+'</body>');}
export async function sampleExcel(s:Sample,r:Round,_lang:'fa'|'en'='en',_kind:'request'|'results'='results',allRounds?:Round[],context?:SampleRow[]){const ExcelJS=(await import('exceljs')).default,wb=new ExcelJS.Workbook();for(const [index,round] of (allRounds||[r]).entries()){const x=reportData(s,round,'en','results',context);const ws=wb.addWorksheet('Dispatch '+(index+1),{views:[{rightToLeft:false}],pageSetup:{orientation:'landscape',paperSize:9,fitToPage:true,fitToWidth:1,fitToHeight:0}});ws.mergeCells('A1:L2');ws.getCell('A1').value=x.title;let n=4;for(const [label,value] of x.info){ws.mergeCells(n,1,n,3);ws.mergeCells(n,4,n,12);ws.getCell(n,1).value=label;ws.getCell(n,4).value=value;n++;}n++;ws.getRow(n).values=x.headers;const header=n;for(const row of x.rows)ws.getRow(++n).values=row;n+=2;for(const [label,value] of x.notes){ws.mergeCells(n,1,n,3);ws.mergeCells(n,4,n,12);ws.getCell(n,1).value=label;ws.getCell(n,4).value=value;ws.getRow(n).height=Math.max(30,Math.ceil(value.length/120)*16);n++;}ws.mergeCells(n+1,1,n+1,12);ws.getCell(n+1,1).value='Occurrences count rejected tests for the same product and batch; physical returns are recorded separately.';if(x.history.length>1){n+=4;ws.getRow(n++).values=['Dispatch date','Customer','Product','Batch','Result','Defects','Corrective action','Return date'];for(const row of x.history)ws.getRow(n++).values=row;}ws.columns.forEach((c,i)=>c.width=i===0?6:i===2?24:14);ws.eachRow(row=>{row.height=Math.max(row.height||0,32);row.eachCell(c=>{c.font={name:'Arial',size:10};c.alignment={vertical:'middle',wrapText:true};c.border={bottom:{style:'thin',color:{argb:'FFBBBBBB'}}};});});ws.getRow(header).font={name:'Arial',size:10,bold:true};ws.getCell('A1').font={name:'Arial',size:17,bold:true};}return new Uint8Array(await wb.xlsx.writeBuffer());}
