import {fields,materialLabels,resultLabels,defectLabels,type Sample,type Round,type Field} from './samples';
type Lang='fa'|'en';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function reportData(s:Sample,r:Round,lang:Lang,kind:'request'|'results'){
 const en=lang==='en',t=(fa:string,eng:string)=>en?eng:fa,b=(p?:{fa:string;en:string})=>p?.[lang]||'',d=(v:string)=>!v?'':en?v:new Intl.DateTimeFormat('fa-IR-u-ca-persian').format(new Date(v+'T12:00:00Z'));
 const info=[[t('نام مشتری','Customer name'),b(s.details.customer_name)],[t('تاریخ درخواست','Request date'),d(s.request_date)],[t('تاریخ نیاز','Required date'),d(s.required_date)],[t('تاریخ ارسال','Dispatch date'),d(r.dispatch_date)],[t('تاریخ اعلام نتیجه','Result date'),d(r.result_date)],[t('تاریخ مصرف در تولید','Production use date'),d(r.production_date)],...Object.entries(fields).filter(([k])=>k!=='customer_name').map(([k,v])=>[v[en?1:0],b(s.details[k as Field])])];
 const headers=[t('ردیف','No.'),t('نوع','Type'),t('شرح','Description'),t('گرید','Grade'),t('کد فنی','Technical number'),t('بچ اصلی','Original batch'),t('بچ آزمون','Test batch'),t('اصلاح','Revision'),t('مقدار','Amount'),t('واحد','Unit'),...(kind==='request'?[t('ویسکوزیته','Viscosity'),t('دانسیته','Density'),t('ضخامت','Thickness')]:[t('نتیجه قلم / مشاهده','Item observation')])];
 const rows=r.items.map((i,n)=>[n+1,materialLabels[i.type][en?1:0],b(i.description),b(i.grade),i.technical_number,i.root_batch,i.batch,i.revision,i.quantity,i.unit,...(kind==='request'?[i.viscosity,i.density,i.thickness]:[b(i.result)])]);
 const notes=[[t('شرایط واقعی آزمون','Actual test conditions'),b(r.conditions)],...(kind==='results'?[[t('نتیجه ترکیب مواد','Combination result'),resultLabels[r.result][en?1:0]],[t('ایرادهای مشاهده‌شده','Observed defects'),r.defects.map(x=>defectLabels[x][en?1:0]).join(' / ')],[t('علت رد','Failure reasons'),b(r.reason)],[t('اقدام اصلاحی','Corrective action'),b(r.action)],[t('توضیحات مشتری / نتیجه','Customer comments / findings'),b(r.comments)]]:[])];
 return {title:kind==='request'?t('درخواست نمونه','Sample request'):t('نتایج آزمون مشتری','Customer test results'),info,headers,rows,notes};
}
export function sampleReportHtml(s:Sample,r:Round,lang:Lang,kind:'request'|'results'){
 const x=reportData(s,r,lang,kind);return `<!doctype html><html lang="${lang}" dir="${lang==='fa'?'rtl':'ltr'}"><meta charset="utf-8"><title>${esc(x.title)}</title><style>@font-face{font-family:Vazir;src:url('/fonts/vazir/Vazir-Variable.woff2')}body{font-family:Vazir,Tahoma,Arial;margin:24px;color:#163b33;font-size:12px}h1{font-size:23px}table{width:100%;border-collapse:collapse;margin:18px 0;table-layout:fixed}td,th{border:1px solid #a7b8b2;padding:8px;overflow-wrap:anywhere;white-space:pre-wrap}th{background:#eaf2ef}dl{display:grid;grid-template-columns:1fr 1fr;gap:10px}dl div{border-bottom:1px solid #dbe4df;padding:8px}dt{font-weight:bold}dd{margin:4px 0;white-space:pre-wrap;overflow-wrap:anywhere}tr{break-inside:avoid}thead{display:table-header-group}@page{size:A4 landscape;margin:12mm}@media print{button{display:none}body{margin:0}}</style><button onclick="window.print()">${lang==='fa'?'چاپ / ذخیره PDF':'Print / Save PDF'}</button><h1>${esc(x.title)}</h1><dl>${x.info.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl><table><thead><tr>${x.headers.map(v=>`<th>${esc(v)}</th>`).join('')}</tr></thead><tbody>${x.rows.map(row=>`<tr>${row.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table><dl>${x.notes.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl></html>`;
}
export async function sampleExcel(s:Sample,r:Round,lang:Lang,kind:'request'|'results',allRounds?:Round[]){
 const ExcelJS=(await import('exceljs')).default;const wb=new ExcelJS.Workbook();for(const [index,round] of (allRounds||[r]).entries()){const x=reportData(s,round,lang,kind);const ws=wb.addWorksheet((lang==='fa'?'آزمون ':'Trial ')+(index+1),{views:[{rightToLeft:lang==='fa'}],pageSetup:{orientation:'landscape',paperSize:9,fitToPage:true,fitToWidth:1,fitToHeight:0}});
 ws.addRow([x.title]);for(const row of x.info)ws.addRow(row);ws.addRow([]);const h=ws.addRow(x.headers);for(const row of x.rows)ws.addRow(row);ws.addRow([]);for(const row of x.notes)ws.addRow(row);
 ws.columns.forEach((c,i)=>c.width=i===2?30:20);ws.eachRow(row=>{row.height=36;row.eachCell(c=>{c.font={name:lang==='fa'?'Vazir':'Arial',size:11};c.alignment={vertical:'middle',wrapText:true};});});h.font={bold:true};}const buf=await wb.xlsx.writeBuffer();return new Uint8Array(buf);
}

export function sampleHistoryHtml(s:Sample,lang:Lang){const pages=s.rounds.map(r=>sampleReportHtml(s,r,lang,'results'));if(!pages.length)return '';return pages[0].replace('</html>',pages.slice(1).map(p=>'<section style="break-before:page">'+p.slice(p.indexOf('<h1>'),p.lastIndexOf('</html>'))+'</section>').join('')+'</html>');}
